
import type { Career } from './types';

export const careers: Career[] = [
    {
        id: "car_1",
        slug: "software-developer",
        title: "Software Developer",
        stream: "Science",
        description: "Designs, develops, and maintains software applications.",
        longDescription: "Software developers are the creative minds behind computer programs. Some develop the applications that allow people to do specific tasks on a computer or another device. Others develop the underlying systems that run the devices or that control networks.",
        skills: ["Java", "Python", "JavaScript", "SQL", "Git", "Problem-Solving"],
        courses: ["B.Tech in Computer Science", "BCA", "MCA"],
        exams: ["JEE Main", "JEE Advanced", "State-level engineering entrances"],
        topColleges: ["IITs", "NITs", "IIITs", "BITS Pilani"],
        admissionProcess: "Admission is primarily through national-level entrance exams like JEE Main and Advanced, followed by counseling.",
        roadmap: "B.Tech -> Internship -> Software Engineer -> Senior Engineer -> Architect/Manager",
        avgSalary: "₹8-12 LPA",
        futureScope: "High demand across industries, with specializations in AI, Cybersecurity, and Cloud."
    },
    {
        id: "car_2",
        slug: "data-scientist",
        title: "Data Scientist",
        stream: "Science",
        description: "Analyzes and interprets complex data to help organizations make better decisions.",
        longDescription: "Data scientists use their analytical, statistical, and programming skills to collect, analyze, and interpret large data sets. They then use this information to develop data-driven solutions to difficult business challenges.",
        skills: ["Python", "R", "SQL", "Machine Learning", "Statistics", "Data Visualization"],
        courses: ["B.Tech in Data Science", "B.Sc in Statistics", "Masters in Data Science"],
        topColleges: ["IITs", "Indian Statistical Institute (ISI)", "Chennai Mathematical Institute (CMI)"],
        admissionProcess: "Varies by course; can include entrance exams like JEE for B.Tech or specific university exams for Masters programs.",
        roadmap: "Degree in relevant field -> Certifications -> Junior Data Scientist -> Senior Data Scientist",
        avgSalary: "₹10-15 LPA",
        futureScope: "Explosive growth in all sectors. Specializations in AI/ML are highly sought after."
    },
    {
        id: "car_3",
        slug: "doctor-mbbs",
        title: "Doctor (MBBS)",
        stream: "Science",
        description: "Diagnoses and treats illnesses and injuries, and provides preventive care.",
        longDescription: "Physicians and surgeons diagnose and treat injuries or illnesses. Physicians examine patients; take medical histories; prescribe medications; and order, perform, and interpret diagnostic tests. Surgeons operate on patients to treat injuries, such as broken bones; diseases, such as cancerous tumors; and deformities, such as cleft palates.",
        skills: ["Medical Knowledge", "Empathy", "Communication", "Attention to Detail", "Problem-Solving"],
        courses: ["MBBS (Bachelor of Medicine, Bachelor of Surgery)"],
        exams: ["NEET (National Eligibility cum Entrance Test)"],
        topColleges: ["AIIMS (Delhi)", "CMC (Vellore)", "JIPMER (Puducherry)"],
        admissionProcess: "Clearing the NEET exam is mandatory for admission to MBBS courses in India, followed by national and state-level counseling.",
        roadmap: "NEET -> MBBS -> Internship -> MD/MS Specialization -> Practice/Hospital Role",
        avgSalary: "₹12-25 LPA (after specialization)",
        futureScope: "Consistently high demand. Opportunities in private practice, hospitals, research, and healthcare management."
    },
    {
        id: "car_4",
        slug: "ux-ui-designer",
        title: "UX/UI Designer",
        stream: "Arts",
        description: "Focuses on the user experience and visual design of digital products.",
        longDescription: "UX (User Experience) and UI (User Interface) designers work to make technology easier and more enjoyable to use. UX designers focus on the user's overall experience, while UI designers focus on the product's layout, visual design, and interactivity.",
        skills: ["Figma", "Sketch", "Adobe XD", "User Research", "Wireframing", "Prototyping"],
        courses: ["Bachelor of Design (B.Des)", "Certification courses in UX/UI"],
        exams: ["NID DAT", "UCEED", "NIFT Entrance Exam"],
        topColleges: ["National Institute of Design (NID)", "IIT Bombay (for IDC)", "NIFT"],
        admissionProcess: "Entrance exams like NID DAT or UCEED are common for design colleges. Many professionals also enter via online certifications and a strong portfolio.",
        roadmap: "Design Degree/Certification -> Internship -> UI/UX Designer -> Senior Designer -> Product Design Lead",
        avgSalary: "₹7-11 LPA",
        futureScope: "Crucial role in all tech companies. Growing need in non-tech sectors as well."
    },
    {
        id: "car_5",
        slug: "chartered-accountant",
        title: "Chartered Accountant",
        stream: "Commerce",
        description: "Manages finances, auditing, taxation, and financial reporting for businesses.",
        longDescription: "Chartered Accountants (CAs) are financial experts who handle a wide range of responsibilities including financial management, auditing, taxation, and corporate law. They are essential for ensuring financial compliance and strategy.",
        skills: ["Accounting Principles", "Auditing", "Taxation Laws", "Financial Analysis", "MS Excel"],
        courses: ["Chartered Accountancy (CA) course by ICAI"],
        exams: ["CA Foundation", "CA Intermediate", "CA Final"],
        topColleges: ["The Institute of Chartered Accountants of India (ICAI) is the sole governing body"],
        admissionProcess: "A three-level examination process (Foundation, Intermediate, Final) conducted by ICAI, along with practical training (articleship).",
        roadmap: "Pass CA Foundation -> Pass CA Intermediate -> 3 Years Articleship -> Pass CA Final -> Become a qualified CA",
        avgSalary: "₹8-15 LPA (can be much higher)",
        futureScope: "Stable demand in every industry. Opportunities in corporate finance, public practice, and consulting."
    },
    {
        id: "car_6",
        slug: "marketing-manager",
        title: "Marketing Manager",
        stream: "Commerce",
        description: "Develops and implements marketing strategies to promote a company's products or services.",
        longDescription: "Marketing managers are responsible for developing, implementing and executing strategic marketing plans for an entire organization (or lines of business and brands within an organization) in order to attract potential customers and retain existing ones.",
        skills: ["Digital Marketing", "SEO/SEM", "Content Strategy", "Market Research", "Communication"],
        courses: ["[BBA (Marketing)", "MBA (Marketing)"],
        topColleges: ["IIMs (Ahmedabad, Bangalore, Calcutta)", "FMS Delhi", "XLRI Jamshedpur"],
        admissionProcess: "For top MBA programs, a bachelor's degree followed by clearing exams like CAT, XAT, or GMAT is required.",
        roadmap: "Bachelor's Degree -> MBA (optional) -> Marketing Executive -> Marketing Manager -> Director",
        avgSalary: "₹10-20 LPA (with MBA)",
        futureScope: "Evolving rapidly with digital trends. High demand for specialists in performance marketing and data analytics."
    },
    {
        id: "car_7",
        slug: "architect",
        title: "Architect",
        stream: "Science",
        description: "Plans and designs buildings and other structures.",
        longDescription: "Architects are responsible for the design and planning of buildings, from initial concepts and sketches to detailed construction drawings. They balance aesthetics, functionality, safety, and budget.",
        skills: ["AutoCAD", "SketchUp", "Revit", "Design Principles", "Project Management"],
        courses: ["Bachelor of Architecture (B.Arch)"],
        exams: ["NATA (National Aptitude Test in Architecture)", "JEE Main (Paper 2)"],
        topColleges: ["School of Planning and Architecture (SPA), Delhi", "IIT Kharagpur", "Sir J.J. College of Architecture, Mumbai"],
        admissionProcess: "Qualifying in NATA or JEE Main Paper 2 is mandatory for B.Arch admissions in India.",
        roadmap: "B.Arch Degree -> Internship -> Junior Architect -> Licensed Architect -> Senior Architect/Own Practice",
        avgSalary: "₹6-10 LPA",
        futureScope: "Growth tied to real estate and infrastructure sectors. Increasing focus on sustainable and green architecture."
    },
    {
        id: "car_8",
        slug: "lawyer",
        title: "Lawyer",
        stream: "Arts",
        description: "Advises and represents clients in legal matters.",
        longDescription: "Lawyers, also known as attorneys, advise and represent individuals, businesses, and government agencies on legal issues and disputes. They can specialize in various areas like corporate law, criminal law, or intellectual property.",
        skills: ["Legal Knowledge", "Analytical Skills", "Logical Reasoning", "Public Speaking", "Writing"],
        courses: ["LLB (3-year or 5-year integrated course)"],
        exams: ["CLAT (Common Law Admission Test)", "AILET", "LSAT India"],
        topColleges: ["National Law School of India University (NLSIU), Bangalore", "NALSAR, Hyderabad", "WBNUJS, Kolkata"],
        admissionProcess: "Admissions to top National Law Universities (NLUs) are through the CLAT exam. Other universities have their own entrance tests.",
        roadmap: "Pass CLAT/other exam -> 5-Year BA LLB -> Bar Council Registration -> Junior Advocate -> Senior Advocate/Corporate Counsel",
        avgSalary: "₹7-15 LPA (highly variable)",
        futureScope: "Diverse opportunities in litigation, corporate firms, judiciary, and public policy. Specializations like Tech Law are emerging."
    }
];

    