
import type { Career } from './types';

export const careers: Career[] = [
    {
        id: "car_1",
        slug: "software-developer",
        title: "Software Developer",
        stream: "Science",
        description: "Designs, develops, and maintains software applications.",
        longDescription: "Software developers are the creative minds behind computer programs. Some develop the applications that allow people to do specific tasks on a computer or another device. Others develop the underlying systems that run the devices or that control networks.",
        skills: ["Java", "Python", "JavaScript", "SQL", "Git", "Problem-Solving"],
        courses: ["B.Tech in Computer Science", "BCA", "MCA"],
        exams: ["JEE Main", "JEE Advanced", "State-level engineering entrances"],
        topColleges: ["IITs", "NITs", "IIITs", "BITS Pilani"],
        admissionProcess: "Admission is primarily through national-level entrance exams like JEE Main and Advanced, followed by counseling.",
        roadmap: "B.Tech -> Internship -> Software Engineer -> Senior Engineer -> Architect/Manager",
        avgSalary: "₹8-12 LPA",
        futureScope: "High demand across industries, with specializations in AI, Cybersecurity, and Cloud."
    },
    {
        id: "car_2",
        slug: "data-scientist",
        title: "Data Scientist",
        stream: "Science",
        description: "Analyzes and interprets complex data to help organizations make better decisions.",
        longDescription: "Data scientists use their analytical, statistical, and programming skills to collect, analyze, and interpret large data sets. They then use this information to develop data-driven solutions to difficult business challenges.",
        skills: ["Python", "R", "SQL", "Machine Learning", "Statistics", "Data Visualization"],
        courses: ["B.Tech in Data Science", "B.Sc in Statistics", "Masters in Data Science"],
        topColleges: ["IITs", "Indian Statistical Institute (ISI)", "Chennai Mathematical Institute (CMI)"],
        admissionProcess: "Varies by course; can include entrance exams like JEE for B.Tech or specific university exams for Masters programs.",
        roadmap: "Degree in relevant field -> Certifications -> Junior Data Scientist -> Senior Data Scientist",
        avgSalary: "₹10-15 LPA",
        futureScope: "Explosive growth in all sectors. Specializations in AI/ML are highly sought after."
    },
    {
        id: "car_3",
        slug: "doctor-mbbs",
        title: "Doctor (MBBS)",
        stream: "Science",
        description: "Diagnoses and treats illnesses and injuries, and provides preventive care.",
        longDescription: "Physicians and surgeons diagnose and treat injuries or illnesses. Physicians examine patients; take medical histories; prescribe medications; and order, perform, and interpret diagnostic tests. Surgeons operate on patients to treat injuries, such as broken bones; diseases, such as cancerous tumors; and deformities, such as cleft palates.",
        skills: ["Medical Knowledge", "Empathy", "Communication", "Attention to Detail", "Problem-Solving"],
        courses: ["MBBS (Bachelor of Medicine, Bachelor of Surgery)"],
        exams: ["NEET (National Eligibility cum Entrance Test)"],
        topColleges: ["AIIMS (Delhi)", "CMC (Vellore)", "JIPMER (Puducherry)"],
        admissionProcess: "Clearing the NEET exam is mandatory for admission to MBBS courses in India, followed by national and state-level counseling.",
        roadmap: "NEET -> MBBS -> Internship -> MD/MS Specialization -> Practice/Hospital Role",
        avgSalary: "₹12-25 LPA (after specialization)",
        futureScope: "Consistently high demand. Opportunities in private practice, hospitals, research, and healthcare management."
    },
    {
        id: "car_4",
        slug: "ux-ui-designer",
        title: "UX/UI Designer",
        stream: "Arts",
        description: "Focuses on the user experience and visual design of digital products.",
        longDescription: "UX (User Experience) and UI (User Interface) designers work to make technology easier and more enjoyable to use. UX designers focus on the user's overall experience, while UI designers focus on the product's layout, visual design, and interactivity.",
        skills: ["Figma", "Sketch", "Adobe XD", "User Research", "Wireframing", "Prototyping"],
        courses: ["Bachelor of Design (B.Des)", "Certification courses in UX/UI"],
        exams: ["NID DAT", "UCEED", "NIFT Entrance Exam"],
        topColleges: ["National Institute of Design (NID)", "IIT Bombay (for IDC)", "NIFT"],
        admissionProcess: "Entrance exams like NID DAT or UCEED are common for design colleges. Many professionals also enter via online certifications and a strong portfolio.",
        roadmap: "Design Degree/Certification -> Internship -> UI/UX Designer -> Senior Designer -> Product Design Lead",
        avgSalary: "₹7-11 LPA",
        futureScope: "Crucial role in all tech companies. Growing need in non-tech sectors as well."
    },
    {
        id: "car_5",
        slug: "chartered-accountant",
        title: "Chartered Accountant",
        stream: "Commerce",
        description: "Manages finances, auditing, taxation, and financial reporting for businesses.",
        longDescription: "Chartered Accountants (CAs) are financial experts who handle a wide range of responsibilities including financial management, auditing, taxation, and corporate law. They are essential for ensuring financial compliance and strategy.",
        skills: ["Accounting Principles", "Auditing", "Taxation Laws", "Financial Analysis", "MS Excel"],
        courses: ["Chartered Accountancy (CA)"],
        exams: ["CA Foundation", "CA Intermediate", "CA Final"],
        topColleges: ["The Institute of Chartered Accountants of India (ICAI) is the sole governing body"],
        admissionProcess: "A three-level examination process (Foundation, Intermediate, Final) conducted by ICAI, along with practical training (articleship).",
        roadmap: "Pass CA Foundation -> Pass CA Intermediate -> 3 Years Articleship -> Pass CA Final -> Become a qualified CA",
        avgSalary: "₹8-15 LPA (can be much higher)",
        futureScope: "Stable demand in every industry. Opportunities in corporate finance, public practice, and consulting."
    },
    {
        id: "car_6",
        slug: "marketing-manager",
        title: "Marketing Manager",
        stream: "Commerce",
        description: "Develops and implements marketing strategies to promote a company's products or services.",
        longDescription: "Marketing managers are responsible for developing, implementing and executing strategic marketing plans for an entire organization (or lines of business and brands within an organization) in order to attract potential customers and retain existing ones.",
        skills: ["Digital Marketing", "SEO/SEM", "Content Strategy", "Market Research", "Communication"],
        courses: ["BBA (Marketing)", "MBA (Marketing)"],
        topColleges: ["IIMs (Ahmedabad, Bangalore, Calcutta)", "FMS Delhi", "XLRI Jamshedpur"],
        admissionProcess: "For top MBA programs, a bachelor's degree followed by clearing exams like CAT, XAT, or GMAT is required.",
        roadmap: "Bachelor's Degree -> MBA (optional) -> Marketing Executive -> Marketing Manager -> Director",
        avgSalary: "₹10-20 LPA (with MBA)",
        futureScope: "Evolving rapidly with digital trends. High demand for specialists in performance marketing and data analytics."
    },
    {
        id: "car_7",
        slug: "architect",
        title: "Architect",
        stream: "Science",
        description: "Plans and designs buildings and other structures.",
        longDescription: "Architects are responsible for the design and planning of buildings, from initial concepts and sketches to detailed construction drawings. They balance aesthetics, functionality, safety, and budget.",
        skills: ["AutoCAD", "SketchUp", "Revit", "Design Principles", "Project Management"],
        courses: ["Bachelor of Architecture (B.Arch)"],
        exams: ["NATA (National Aptitude Test in Architecture)", "JEE Main (Paper 2)"],
        topColleges: ["School of Planning and Architecture (SPA), Delhi", "IIT Kharagpur", "Sir J.J. College of Architecture, Mumbai"],
        admissionProcess: "Qualifying in NATA or JEE Main Paper 2 is mandatory for B.Arch admissions in India.",
        roadmap: "B.Arch Degree -> Internship -> Junior Architect -> Licensed Architect -> Senior Architect/Own Practice",
        avgSalary: "₹6-10 LPA",
        futureScope: "Growth tied to real estate and infrastructure sectors. Increasing focus on sustainable and green architecture."
    },
    {
        id: "car_8",
        slug: "lawyer",
        title: "Lawyer",
        stream: "Arts",
        description: "Advises and represents clients in legal matters.",
        longDescription: "Lawyers, also known as attorneys, advise and represent individuals, businesses, and government agencies on legal issues and disputes. They can specialize in various areas like corporate law, criminal law, or intellectual property.",
        skills: ["Legal Knowledge", "Analytical Skills", "Logical Reasoning", "Public Speaking", "Writing"],
        courses: ["LLB (3-year or 5-year integrated course)"],
        exams: ["CLAT (Common Law Admission Test)", "AILET", "LSAT India"],
        topColleges: ["National Law School of India University (NLSIU), Bangalore", "NALSAR, Hyderabad", "WBNUJS, Kolkata"],
        admissionProcess: "Admissions to top National Law Universities (NLUs) are through the CLAT exam. Other universities have their own entrance tests.",
        roadmap: "Pass CLAT/other exam -> 5-Year BA LLB -> Bar Council Registration -> Junior Advocate -> Senior Advocate/Corporate Counsel",
        avgSalary: "₹7-15 LPA (highly variable)",
        futureScope: "Diverse opportunities in litigation, corporate firms, judiciary, and public policy. Specializations like Tech Law are emerging."
    },
    {
        id: 'car_9',
        slug: 'civil-engineer',
        title: 'Civil Engineer',
        stream: 'Science',
        description: 'Designs, builds, and maintains infrastructure projects.',
        longDescription: 'Civil engineers conceive, design, build, supervise, operate, construct, and maintain infrastructure projects and systems in the public and private sector, including roads, buildings, airports, tunnels, dams, bridges, and systems for water supply and sewage treatment.',
        skills: ['AutoCAD', 'Structural Analysis', 'Project Management', 'Surveying', 'Geotechnical Engineering'],
        courses: ['B.Tech in Civil Engineering'],
        exams: ['JEE Main', 'JEE Advanced', 'State CETs'],
        topColleges: ['IIT Bombay', 'IIT Delhi', 'IIT Madras', 'NIT Trichy'],
        admissionProcess: 'Admission is based on ranks in national-level entrance exams like JEE, followed by centralized counseling.',
        roadmap: 'B.Tech -> Site Engineer -> Project Manager -> Chief Engineer',
        avgSalary: '₹6-9 LPA',
        futureScope: 'Essential for infrastructure development, with roles in government and private sectors. Focus on smart cities and sustainable infrastructure is growing.'
    },
    {
        id: 'car_10',
        slug: 'pharmacist',
        title: 'Pharmacist',
        stream: 'Science',
        description: 'Dispenses medications and advises on their safe use.',
        longDescription: 'Pharmacists dispense prescription medications to patients and offer expertise in the safe use of prescriptions. They also may conduct health and wellness screenings, provide immunizations, and oversee the medications given to patients.',
        skills: ['Pharmacology', 'Medical Compliance', 'Patient Counseling', 'Chemistry', 'Attention to Detail'],
        courses: ['B.Pharm', 'D.Pharm', 'M.Pharm'],
        exams: ['NEET (for some institutes)', 'State Pharmacy Entrances (e.g., MHT-CET)', 'GPAT (for M.Pharm)'],
        topColleges: ['Jamia Hamdard', 'Panjab University', 'NIPER Mohali'],
        admissionProcess: 'Admissions are through national or state-level entrance exams. A license from the Pharmacy Council of India is required to practice.',
        roadmap: 'D.Pharm/B.Pharm -> Registered Pharmacist -> M.Pharm (optional) -> Hospital/Retail/Industrial Pharmacist',
        avgSalary: '₹3-5 LPA',
        futureScope: 'Stable demand in healthcare. Opportunities in retail, hospitals, pharmaceutical industry (R&D, manufacturing), and academia.'
    },
    {
        id: 'car_11',
        slug: 'psychologist',
        title: 'Psychologist',
        stream: 'Arts',
        description: 'Studies human mind and behavior to help people.',
        longDescription: 'Psychologists study the human mind and behavior, and they use this knowledge to help people with mental health issues, relationship problems, and other life challenges. They can work in clinical, counseling, or research settings.',
        skills: ['Empathy', 'Active Listening', 'Analytical Skills', 'Communication', 'Patience'],
        courses: ['BA in Psychology', 'MA/M.Sc in Psychology', 'M.Phil', 'PhD'],
        topColleges: ['Lady Shri Ram College (DU)', 'Christ University', 'TISS Mumbai', 'NIMHANS Bangalore'],
        admissionProcess: 'Merit-based for UG courses. Entrance exams for most MA and all M.Phil/PhD programs. A license from RCI is needed for clinical practice.',
        roadmap: 'BA (Psychology) -> MA (Psychology) -> M.Phil (Clinical Psychology) -> Licensed Psychologist',
        avgSalary: '₹4-8 LPA (with Masters)',
        futureScope: 'Increasing awareness about mental health is driving demand. Specializations in child, organizational, or sports psychology are growing.'
    },
    {
        id: 'car_12',
        slug: 'graphic-designer',
        title: 'Graphic Designer',
        stream: 'Arts',
        description: 'Creates visual concepts to communicate ideas.',
        longDescription: 'Graphic designers create visual concepts, using computer software or by hand, to communicate ideas that inspire, inform, and captivate consumers. They develop the overall layout and production design for applications such as advertisements, brochures, magazines, and reports.',
        skills: ['Adobe Creative Suite', 'Typography', 'Color Theory', 'Creativity', 'Communication'],
        courses: ['B.Des in Graphic Design', 'Bachelor of Fine Arts (BFA)'],
        exams: ['NID DAT', 'UCEED', 'NIFT'],
        topColleges: ['National Institute of Design (NID)', 'MIT Institute of Design', 'Srishti Institute of Art, Design and Technology'],
        admissionProcess: 'Based on scores from design entrance exams, which include a portfolio review and interview.',
        roadmap: 'Design Degree -> Junior Designer -> Senior Designer -> Art Director',
        avgSalary: '₹4-7 LPA',
        futureScope: 'High demand in marketing, media, and tech. The rise of digital media has created many opportunities.'
    },
    {
        id: 'car_13',
        slug: 'investment-banker',
        title: 'Investment Banker',
        stream: 'Commerce',
        description: 'Helps companies and governments raise capital.',
        longDescription: 'Investment bankers help corporations, governments, and other entities plan and manage the financial aspects of large projects. They are experts in raising capital by issuing stocks or bonds and in facilitating mergers and acquisitions.',
        skills: ['Financial Modeling', 'Valuation', 'Negotiation', 'Analytical Skills', 'High-Stakes Decision Making'],
        courses: ['BBA/B.Com', 'MBA in Finance', 'CA', 'CFA'],
        topColleges: ['IIMs (A, B, C)', 'ISB Hyderabad', 'FMS Delhi', 'XLRI'],
        admissionProcess: 'Typically requires an MBA from a top-tier business school. Strong academic background and internships are crucial.',
        roadmap: 'UG Degree -> MBA -> Analyst -> Associate -> Vice President -> Managing Director',
        avgSalary: '₹15-40 LPA+ (highly variable with bonuses)',
        futureScope: 'A high-pressure, high-reward field. Tied to economic growth. Opportunities in private equity and venture capital as well.'
    },
    {
        id: 'car_14',
        slug: 'journalist',
        title: 'Journalist',
        stream: 'Arts',
        description: 'Researches, writes, and reports news stories.',
        longDescription: 'Journalists research, write, and report on current events and issues for newspapers, magazines, websites, television, and radio. They strive to present information in a fair, accurate, and unbiased manner.',
        skills: ['Writing', 'Research', 'Interviewing', 'Ethics', 'Communication'],
        courses: ['Bachelor of Journalism and Mass Communication (BJMC)'],
        topColleges: ['Indian Institute of Mass Communication (IIMC)', 'Symbiosis Institute of Media & Communication', 'ACJ Chennai'],
        admissionProcess: 'Admission is through entrance exams conducted by individual universities and colleges.',
        roadmap: 'BJMC/MA -> Internship -> Reporter/Sub-editor -> Senior Correspondent -> Editor',
        avgSalary: '₹4-8 LPA',
        futureScope: 'The media landscape is changing with digital media. Roles in data journalism, podcasting, and digital content creation are growing.'
    },
    {
        id: 'car_15',
        slug: 'ai-ml-engineer',
        title: 'AI/ML Engineer',
        stream: 'Science',
        description: 'Builds and deploys Artificial Intelligence and Machine Learning models.',
        longDescription: 'AI/ML Engineers are specialized software engineers who work with large datasets and complex algorithms to design, build, and train models that can be used for tasks like prediction, classification, and generation. They are at the forefront of technological innovation.',
        skills: ['Python', 'TensorFlow/PyTorch', 'Statistics', 'Algorithms', 'Data Structures', 'NLP'],
        courses: ['B.Tech in AI & ML', 'B.Tech in Computer Science', 'Masters in AI'],
        exams: ['JEE Main', 'JEE Advanced', 'GATE'],
        topColleges: ['IITs', 'IIIT Hyderabad', 'NITs'],
        admissionProcess: 'Requires a strong foundation in computer science and mathematics. Admission is through competitive engineering entrance exams.',
        roadmap: 'B.Tech -> ML Engineer -> Senior ML Engineer -> AI Scientist/Architect',
        avgSalary: '₹12-20 LPA',
        futureScope: 'One of the fastest-growing and highest-demand fields in technology, impacting every industry from healthcare to finance.'
    },
    {
        id: 'car_16',
        slug: 'product-manager',
        title: 'Product Manager',
        stream: 'Commerce',
        description: 'Guides the success of a product and leads the cross-functional team.',
        longDescription: 'Product Managers are the CEOs of their products. They are responsible for setting the strategy, roadmap, and feature definition for a product or product line. They bridge the gap between business, technology, and user experience.',
        skills: ['Strategy', 'Leadership', 'Communication', 'User Research', 'Data Analysis', 'Prioritization'],
        courses: ['B.Tech', 'MBA'],
        topColleges: ['No specific degree, but IIMs/IITs are common backgrounds'],
        admissionProcess: 'Often a mid-career role. People transition from engineering, design, or business analysis. An MBA can be a common entry point.',
        roadmap: 'Engineer/Analyst -> Associate PM -> Product Manager -> Senior PM -> Director of Product',
        avgSalary: '₹15-25 LPA',
        futureScope: 'A critical role in any tech-driven company. The demand for skilled product managers is extremely high.'
    },
    {
        id: 'car_17',
        slug: 'management-consultant',
        title: 'Management Consultant',
        stream: 'Commerce',
        description: 'Helps organizations solve problems and improve performance.',
        longDescription: 'Management consultants are hired by companies to provide expert advice on how to solve complex business problems, improve performance, and maximize growth. They work on a project basis across various industries.',
        skills: ['Problem-Solving', 'Analytical Skills', 'Communication', 'Presentation', 'Teamwork'],
        courses: ['B.Tech', 'B.Com', 'MBA'],
        topColleges: ['IITs', 'IIMs (A, B, C)', 'ISB Hyderabad', 'SRCC'],
        admissionProcess: 'Recruitment is highly competitive, often from top-tier undergraduate and business schools. Involves rigorous case study interviews.',
        roadmap: 'UG/MBA -> Analyst -> Consultant -> Project Lead -> Partner',
        avgSalary: '₹18-30 LPA (at top firms)',
        futureScope: 'Excellent career trajectory and exit opportunities into leadership roles in various industries.'
    },
    {
        id: 'car_18',
        slug: 'social-media-manager',
        title: 'Social Media Manager',
        stream: 'Arts',
        description: 'Manages a brand\'s online presence and engagement on social media.',
        longDescription: 'A Social Media Manager is responsible for creating and publishing content on all social media platforms, including Facebook, Twitter, and Instagram, to grow an audience, build brand awareness, and ultimately, boost sales.',
        skills: ['Content Creation', 'Copywriting', 'SEO', 'Analytics', 'Community Management'],
        courses: ['BA in Mass Communication', 'BBA', 'Digital Marketing Certifications'],
        topColleges: ['No specific requirement, practical skills are more important.'],
        admissionProcess: 'Entry is often based on demonstrated skills, portfolio of work, and certifications. Internships are a common starting point.',
        roadmap: 'Internship -> Social Media Executive -> Social Media Manager -> Head of Social/Digital',
        avgSalary: '₹5-9 LPA',
        futureScope: 'An integral part of modern marketing. The role is constantly evolving with new platforms and technologies.'
    },
    {
        id: 'car_19',
        slug: 'fashion-designer',
        title: 'Fashion Designer',
        stream: 'Arts',
        description: 'Designs clothing and accessories.',
        longDescription: 'Fashion designers create original clothing, accessories, and footwear. They sketch designs, select fabrics and patterns, and give instructions on how to make the products they designed.',
        skills: ['Creativity', 'Sketching', 'Fabric Knowledge', 'Sewing', 'Trend Awareness'],
        courses: ['Bachelor of Design (B.Des) in Fashion Design'],
        exams: ['NIFT Entrance Exam', 'NID DAT'],
        topColleges: ['National Institute of Fashion Technology (NIFT)', 'Pearl Academy', 'NID'],
        admissionProcess: 'Admission is through competitive entrance exams which test creativity, drawing skills, and general aptitude.',
        roadmap: 'B.Des -> Internship with a designer -> Assistant Designer -> Designer -> Own Label/Head Designer',
        avgSalary: '₹4-10 LPA (highly variable)',
        futureScope: 'Competitive field with opportunities in export houses, retail brands, and independent labels. Sustainable fashion is a growing niche.'
    },
    {
        id: 'car_20',
        slug: 'veterinarian',
        title: 'Veterinarian',
        stream: 'Science',
        description: 'Provides medical care for animals.',
        longDescription: 'Veterinarians care for the health of animals. They diagnose, treat, and research medical conditions and diseases of pets, livestock, and other animals.',
        skills: ['Animal Handling', 'Medical Knowledge', 'Surgery', 'Empathy', 'Communication'],
        courses: ['Bachelor of Veterinary Science & Animal Husbandry (B.V.Sc & AH)'],
        exams: ['NEET (in some states)', 'All India Pre-Veterinary Test (AIPVT)'],
        topColleges: ['Indian Veterinary Research Institute (IVRI)', 'Tamil Nadu Veterinary and Animal Sciences University (TANUVAS)'],
        admissionProcess: 'Based on scores in NEET or state-level veterinary entrance exams.',
        roadmap: 'B.V.Sc -> Junior Vet -> Senior Vet in a clinic/hospital or own practice.',
        avgSalary: '₹5-8 LPA',
        futureScope: 'Growing demand due to increased pet ownership and awareness. Opportunities in private practice, government services, and research.'
    }
];
