import type { Career, Question } from './types';

export const careers: Career[] = [
  {
    id: '1',
    slug: 'software-engineering',
    title: 'Software Engineering',
    stream: 'Engineering',
    description: 'Design, develop, and maintain software systems. A creative and problem-solving field.',
    longDescription: 'Software engineering is a systematic, disciplined, and quantifiable approach to the design, development, operation, and maintenance of software. It involves applying engineering principles to software development, making it a highly sought-after and rewarding career path for those who enjoy logic, problem-solving, and creating things.',
    skills: ['Programming (Python, Java, C++)', 'Data Structures & Algorithms', 'Version Control (Git)', 'Problem Solving'],
    courses: ['B.Tech in Computer Science', 'BCA', 'Online Coding Bootcamps'],
    roadmap: 'Education (B.Tech) -> Internships -> Junior Developer -> Senior Developer/Architect',
    avgSalary: '$110,000/year',
    futureScope: 'Extremely high demand with growth in AI, Machine Learning, and Cybersecurity.',
  },
  {
    id: '2',
    slug: 'ux-ui-design',
    title: 'UX/UI Design',
    stream: 'Design',
    description: 'Create user-friendly and visually appealing digital products.',
    longDescription: 'UX/UI Design focuses on creating seamless and enjoyable experiences for users of digital products. UX (User Experience) design is about the overall feel of the experience, while UI (User Interface) design is about how the product\'s interfaces look and function. It\'s a blend of creativity, empathy, and technical skill.',
    skills: ['Figma/Sketch', 'User Research', 'Wireframing & Prototyping', 'Visual Design'],
    courses: ['B.Des in Design', 'Certified Courses in UX/UI', 'Portfolio Development'],
    roadmap: 'Learn Design Tools -> Build Portfolio -> Internship -> UI/UX Designer -> Product Designer',
    avgSalary: '$95,000/year',
    futureScope: 'Growing rapidly as businesses prioritize user-centric products.',
  },
  {
    id: '3',
    slug: 'data-science',
    title: 'Data Science',
    stream: 'Science',
    description: 'Analyze large datasets to extract meaningful insights and drive business decisions.',
    longDescription: 'Data science is an interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from structured and unstructured data. It combines statistics, computer science, and domain expertise to turn data into a valuable asset.',
    skills: ['Python/R', 'SQL', 'Machine Learning', 'Statistics', 'Data Visualization'],
    courses: ['B.Tech in Data Science/AI', 'M.Sc in Statistics', 'Data Science Certifications'],
    roadmap: 'Degree in relevant field -> Learn programming & stats -> Projects -> Data Analyst -> Data Scientist',
    avgSalary: '$120,000/year',
    futureScope: 'One of the fastest-growing fields, integral to AI and business intelligence.',
  },
  {
    id: '4',
    slug: 'doctor',
    title: 'Doctor',
    stream: 'Medicine',
    description: 'Diagnose and treat illnesses, and work to keep people healthy.',
    longDescription: 'Being a doctor is a noble profession dedicated to health and well-being. It requires extensive education and training to diagnose patient conditions, prescribe treatments, and provide primary care or specialize in areas like surgery, pediatrics, or cardiology. It is a demanding yet highly respected and fulfilling career.',
    skills: ['Medical Knowledge', 'Attention to Detail', 'Empathy', 'Communication'],
    courses: ['MBBS (Bachelor of Medicine, Bachelor of Surgery)', 'NEET exam for entry'],
    roadmap: 'Clear NEET -> 5.5 years of MBBS -> Internship -> MD/MS for specialization',
    avgSalary: '$208,000+/year',
    futureScope: 'Consistently high demand worldwide with opportunities for specialization and research.',
  },
  {
    id: '5',
    slug: 'marketing-manager',
    title: 'Marketing Manager',
    stream: 'Business',
    description: 'Plan and execute marketing campaigns to promote a brand or product.',
    longDescription: 'Marketing managers are responsible for developing, implementing, and executing strategic marketing plans for an entire organization (or lines of business and brands within an organization) in order to attract potential customers and retain existing ones.',
    skills: ['SEO/SEM', 'Content Strategy', 'Social Media Marketing', 'Data Analysis'],
    courses: ['MBA in Marketing', 'BBA', 'Digital Marketing Certifications'],
    roadmap: 'Bachelor\'s Degree -> Entry-level marketing role -> Marketing Specialist -> Marketing Manager',
    avgSalary: '$105,000/year',
    futureScope: 'Strong growth, especially in digital and data-driven marketing roles.',
  },
  {
    id: '6',
    slug: 'financial-analyst',
    title: 'Financial Analyst',
    stream: 'Commerce',
    description: 'Analyze financial data to help companies make business decisions.',
    longDescription: 'Financial analysts guide businesses and individuals in decisions about expending money to attain profit. They assess the performance of stocks, bonds, and other types of investments.',
    skills: ['Financial Modeling', 'Excel', 'Valuation', 'Statistics'],
    courses: ['B.Com/BBA in Finance', 'CFA (Chartered Financial Analyst)', 'MBA in Finance'],
    roadmap: 'Finance Degree -> Internship -> Junior Analyst -> Senior Analyst -> Portfolio Manager',
    avgSalary: '$92,000/year',
    futureScope: 'Stable demand in corporate finance, investment banking, and asset management.',
  },
  {
    id: '7',
    slug: 'architect',
    title: 'Architect',
    stream: 'Design',
    description: 'Plan and design buildings and other structures, combining art and science.',
    longDescription: 'Architects are professionals trained in the art and science of building design. They develop concepts for structures and turn those concepts into reality through detailed plans and drawings. Their work involves creativity, precision, and a deep understanding of construction.',
    skills: ['AutoCAD/Revit', 'Design Principles', 'Project Management', 'Building Codes'],
    courses: ['B.Arch (Bachelor of Architecture)', 'M.Arch', 'State Licensure'],
    roadmap: 'B.Arch Degree -> Internship -> Licensure Exam -> Licensed Architect -> Firm Partner',
    avgSalary: '$88,000/year',
    futureScope: 'Growth tied to construction industry, with a rising focus on sustainable design.',
  },
  {
    id: '8',
    slug: 'lawyer',
    title: 'Lawyer',
    stream: 'Humanities',
    description: 'Advise and represent clients in legal matters.',
    longDescription: 'Lawyers, also known as attorneys, act as both advocates and advisors. They represent clients in criminal and civil trials, and provide legal advice on a wide range of issues. The profession requires strong analytical and communication skills, as well as a commitment to justice.',
    skills: ['Legal Research', 'Argumentation', 'Negotiation', 'Attention to Detail'],
    courses: ['LLB (Bachelor of Laws)', 'LLM (Master of Laws)', 'Bar Examination'],
    roadmap: 'Undergraduate Degree -> Law School (JD/LLB) -> Bar Exam -> Associate at a firm -> Partner or Corporate Counsel',
    avgSalary: '$135,000/year',
    futureScope: 'Consistent demand with specialization opportunities in tech, environmental, and corporate law.',
  },
];

export const quizQuestions: Question[] = [
  {
    id: 'q1',
    text: 'When faced with a complex problem, you prefer to...',
    options: [
      { text: 'Break it down into smaller, logical steps.', value: 'analytical' },
      { text: 'Brainstorm creative and unconventional solutions.', value: 'creative' },
      { text: 'Collaborate with others to find a solution together.', value: 'social' },
      { text: 'Build or create a tangible solution with your hands.', value: 'technical' },
    ],
  },
  {
    id: 'q2',
    text: 'You are most energized by...',
    options: [
      { text: 'Solving puzzles and finding patterns in data.', value: 'analytical' },
      { text: 'Expressing yourself through art, music, or writing.', value: 'creative' },
      { text: 'Helping and understanding people\'s needs.', value: 'social' },
      { text: 'Understanding the mechanics of how things work.', value: 'technical' },
    ],
  },
  {
    id: 'q3',
    text: 'Your ideal work environment would be...',
    options: [
      { text: 'A structured office with clear goals and metrics.', value: 'business' },
      { text: 'A dynamic and vibrant studio or workshop.', value: 'creative' },
      { text: 'A hospital or clinic where you can directly help people.', value: 'caring' },
      { text: 'A courtroom or a formal, professional setting.', value: 'humanities' },
    ],
  },
  {
    id: 'q4',
    text: 'Which of these activities sounds most appealing?',
    options: [
      { text: 'Developing a strategy for a marketing campaign.', value: 'business' },
      { text: 'Designing a poster or a website layout.', value: 'creative' },
      { text: 'Debating a complex ethical or legal issue.', value: 'humanities' },
      { text: 'Conducting a scientific experiment to test a hypothesis.', value: 'analytical' },
    ],
  },
  {
    id: 'q5',
    text: 'You feel most successful when you...',
    options: [
      { text: 'Have optimized a process for maximum efficiency.', value: 'analytical' },
      { text: 'Have created something beautiful and functional.', value: 'creative' },
      { text: 'Have made a positive impact on someone\'s health or life.', value: 'caring' },
      { text: 'Have successfully argued a point or won a debate.', value: 'humanities' },
    ],
  },
  {
    id: 'q6',
    text: 'What kind of topics do you enjoy reading about?',
    options: [
        { text: 'The latest tech innovations and gadgets.', value: 'technical' },
        { text: 'Business news and market trends.', value: 'business' },
        { text: 'Art history, philosophy, or social justice.', value: 'humanities' },
        { text: 'Medical breakthroughs and human biology.', value: 'caring' },
    ],
  },
  {
      id: 'q7',
      text: 'In a group project, you are most likely to take on the role of...',
      options: [
          { text: 'The leader who organizes the plan and delegates tasks.', value: 'business' },
          { text: 'The researcher who gathers and analyzes information.', value: 'analytical' },
          { text: 'The designer who handles the visual presentation.', value: 'creative' },
          { text: 'The mediator who ensures everyone is heard and working together.', value: 'social' },
      ],
  },
  {
      id: 'q8',
      text: 'Which of these would frustrate you the most?',
      options: [
          { text: 'A vague brief with no clear objectives.', value: 'analytical' },
          { text: 'Working on a repetitive, uncreative task.', value: 'creative' },
          { text: 'Dealing with a system that is inefficient or illogical.', value: 'technical' },
          { text: 'A project with no real-world impact or benefit to people.', value: 'social' },
      ],
  },
  {
      id: 'q9',
      text: 'What subject did you enjoy most in school?',
      options: [
          { text: 'Math or Physics', value: 'analytical' },
          { text: 'Art or English', value: 'creative' },
          { text: 'Biology or Chemistry', value: 'caring' },
          { text: 'History or Economics', value: 'humanities' },
      ],
  },
  {
      id: 'q10',
      text: 'You are motivated by...',
      options: [
          { text: 'Achieving measurable results and growth.', value: 'business' },
          { text: 'Bringing an idea to life.', value: 'creative' },
          { text: 'Ensuring fairness and upholding rules.', value: 'humanities' },
          { text: 'Mastering a complex system or technology.', value: 'technical' },
      ],
  },
];
