
import type { Career, Question } from './types';

export const careers: Career[] = [
  {
    id: '1',
    slug: 'software-engineering',
    title: 'Software Engineering',
    stream: 'Science',
    description: 'Design, develop, and maintain software systems. A creative and problem-solving field.',
    longDescription: 'Software engineering is a systematic, disciplined, and quantifiable approach to the design, development, operation, and maintenance of software. It involves applying engineering principles to software development, making it a highly sought-after and rewarding career path for those who enjoy logic, problem-solving, and creating things.',
    skills: ['Programming (Python, Java, C++)', 'Data Structures & Algorithms', 'Version Control (Git)', 'Problem Solving'],
    courses: ['B.Tech in Computer Science', 'BCA', 'Online Coding Bootcamps'],
    exams: ['JEE Main & Advanced', 'GATE (for M.Tech)'],
    topColleges: ['IIT Bombay', 'IIT Delhi', 'IIT Madras', 'IIIT Hyderabad', 'NIT Trichy'],
    admissionProcess: 'Admission to top engineering colleges is primarily through competitive entrance exams like JEE Main and JEE Advanced. Some universities have their own entrance tests.',
    roadmap: 'Education (B.Tech) -> Internships -> Junior Developer -> Senior Developer/Architect',
    avgSalary: '₹8 - 20 LPA',
    futureScope: 'Extremely high demand with growth in AI, Machine Learning, and Cybersecurity.',
  },
  {
    id: '2',
    slug: 'ux-ui-design',
    title: 'UX/UI Design',
    stream: 'Arts',
    description: 'Create user-friendly and visually appealing digital products.',
    longDescription: 'UX/UI Design focuses on creating seamless and enjoyable experiences for users of digital products. UX (User Experience) design is about the overall feel of the experience, while UI (User Interface) design is about how the product\'s interfaces look and function. It\'s a blend of creativity, empathy, and technical skill.',
    skills: ['Figma/Sketch', 'User Research', 'Wireframing & Prototyping', 'Visual Design'],
    courses: ['B.Des in Design', 'Certified Courses in UX/UI', 'Portfolio Development'],
    exams: ['UCEED', 'NID DAT'],
    topColleges: ['National Institute of Design (NID)', 'IDC School of Design (IIT Bombay)', 'MIT Institute of Design', 'Srishti Institute of Art, Design and Technology'],
    admissionProcess: 'Admission is based on entrance exams like UCEED and NID DAT, which are followed by studio tests, interviews, and portfolio reviews.',
    roadmap: 'Learn Design Tools -> Build Portfolio -> Internship -> UI/UX Designer -> Product Designer',
    avgSalary: '₹6 - 15 LPA',
    futureScope: 'Growing rapidly as businesses prioritize user-centric products.',
  },
  {
    id: '3',
    slug: 'data-science',
    title: 'Data Science',
    stream: 'Science',
    description: 'Analyze large datasets to extract meaningful insights and drive business decisions.',
    longDescription: 'Data science is an interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from structured and unstructured data. It combines statistics, computer science, and domain expertise to turn data into a valuable asset.',
    skills: ['Python/R', 'SQL', 'Machine Learning', 'Statistics', 'Data Visualization'],
    courses: ['B.Tech in Data Science/AI', 'M.Sc in Statistics', 'Data Science Certifications'],
    exams: ['JEE Main & Advanced', 'GATE (for M.Tech)'],
    topColleges: ['IIT Madras (BS in Data Science)', 'Chennai Mathematical Institute (CMI)', 'Indian Statistical Institute (ISI) Kolkata', 'IIM Calcutta (PGDBA)'],
    admissionProcess: 'Entry is typically through engineering entrance exams for undergraduate courses or specific entrance tests for postgraduate programs like CAT and GATE.',
    roadmap: 'Degree in relevant field -> Learn programming & stats -> Projects -> Data Analyst -> Data Scientist',
    avgSalary: '₹10 - 25 LPA',
    futureScope: 'One of the fastest-growing fields, integral to AI and business intelligence.',
  },
  {
    id: '4',
    slug: 'doctor',
    title: 'Doctor',
    stream: 'Science',
    description: 'Diagnose and treat illnesses, and work to keep people healthy.',
    longDescription: 'Being a doctor is a noble profession dedicated to health and well-being. It requires extensive education and training to diagnose patient conditions, prescribe treatments, and provide primary care or specialize in areas like surgery, pediatrics, or cardiology. It is a demanding yet highly respected and fulfilling career.',
    skills: ['Medical Knowledge', 'Attention to Detail', 'Empathy', 'Communication'],
    courses: ['MBBS (Bachelor of Medicine, Bachelor of Surgery)'],
    exams: ['NEET-UG', 'NEET-PG', 'NEXT'],
    topColleges: ['AIIMS Delhi', 'Christian Medical College (CMC) Vellore', 'Armed Forces Medical College (AFMC) Pune', 'JIPMER Puducherry'],
    admissionProcess: 'Admission to MBBS courses is through the national-level entrance exam, NEET-UG. Admission to postgraduate courses is via NEET-PG.',
    roadmap: 'Clear NEET -> 5.5 years of MBBS -> Internship -> MD/MS for specialization',
    avgSalary: '₹12 - 30+ LPA',
    futureScope: 'Consistently high demand worldwide with opportunities for specialization and research.',
  },
  {
    id: '5',
    slug: 'marketing-manager',
    title: 'Marketing Manager',
    stream: 'Commerce',
    description: 'Plan and execute marketing campaigns to promote a brand or product.',
    longDescription: 'Marketing managers are responsible for developing, implementing, and executing strategic marketing plans for an entire organization (or lines of business and brands within an organization) in order to attract potential customers and retain existing ones.',
    skills: ['SEO/SEM', 'Content Strategy', 'Social Media Marketing', 'Data Analysis'],
    courses: ['MBA in Marketing', 'BBA', 'Digital Marketing Certifications'],
    exams: ['CAT', 'XAT', 'GMAT (for MBA)'],
    topColleges: ['IIM Ahmedabad', 'IIM Bangalore', 'IIM Calcutta', 'XLRI Jamshedpur', 'FMS Delhi'],
    admissionProcess: 'For top MBA programs, admission is through competitive exams like CAT, followed by group discussions and personal interviews.',
    roadmap: 'Bachelor\'s Degree -> Entry-level marketing role -> Marketing Specialist -> Marketing Manager',
    avgSalary: '₹10 - 25 LPA',
    futureScope: 'Strong growth, especially in digital and data-driven marketing roles.',
  },
  {
    id: '6',
    slug: 'financial-analyst',
    title: 'Financial Analyst',
    stream: 'Commerce',
    description: 'Analyze financial data to help companies make business decisions.',
    longDescription: 'Financial analysts guide businesses and individuals in decisions about expending money to attain profit. They assess the performance of stocks, bonds, and other types of investments.',
    skills: ['Financial Modeling', 'Excel', 'Valuation', 'Statistics'],
    courses: ['B.Com/BBA in Finance', 'CFA (Chartered Financial Analyst)', 'MBA in Finance'],
    topColleges: ['Shri Ram College of Commerce (SRCC), Delhi', 'IIMs (for MBA)', 'St. Xavier\'s College, Mumbai', 'Christ University, Bangalore'],
    admissionProcess: 'Admission to B.Com/BBA is usually based on Class 12 marks. CFA is a professional certification. MBA admissions are through exams like CAT.',
    roadmap: 'Finance Degree -> Internship -> Junior Analyst -> Senior Analyst -> Portfolio Manager',
    avgSalary: '₹5 - 15 LPA',
    futureScope: 'Stable demand in corporate finance, investment banking, and asset management.',
  },
  {
    id: '7',
    slug: 'architect',
    title: 'Architect',
    stream: 'Science',
    description: 'Plan and design buildings and other structures, combining art and science.',
    longDescription: 'Architects are professionals trained in the art and science of building design. They develop concepts for structures and turn those concepts into reality through detailed plans and drawings. Their work involves creativity, precision, and a deep understanding of construction.',
    skills: ['AutoCAD/Revit', 'Design Principles', 'Project Management', 'Building Codes'],
    courses: ['B.Arch (Bachelor of Architecture)', 'M.Arch', 'State Licensure'],
    exams: ['NATA', 'JEE Main (Paper 2)'],
    topColleges: ['School of Planning and Architecture (SPA), Delhi', 'IIT Kharagpur', 'Sir J.J. College of Architecture, Mumbai', 'CEPT University, Ahmedabad'],
    admissionProcess: 'Admission to B.Arch is through NATA or JEE Main Paper 2 scores, which test drawing skills, physics, chemistry, and math.',
    roadmap: 'B.Arch Degree -> Internship -> Licensure Exam -> Licensed Architect -> Firm Partner',
    avgSalary: '₹5 - 12 LPA',
    futureScope: 'Growth tied to construction industry, with a rising focus on sustainable design.',
  },
  {
    id: '8',
    slug: 'lawyer',
    title: 'Lawyer',
    stream: 'Arts',
    description: 'Advise and represent clients in legal matters.',
    longDescription: 'Lawyers, also known as attorneys, act as both advocates and advisors. They represent clients in criminal and civil trials, and provide legal advice on a wide range of issues. The profession requires strong analytical and communication skills, as well as a commitment to justice.',
    skills: ['Legal Research', 'Argumentation', 'Negotiation', 'Attention to Detail'],
    courses: ['LLB (Bachelor of Laws)', 'LLM (Master of Laws)', 'Bar Examination'],
    exams: ['CLAT', 'AILET', 'LSAT India'],
    topColleges: ['National Law School of India University (NLSIU), Bangalore', 'NALSAR University of Law, Hyderabad', 'Symbiosis Law School, Pune', 'Faculty of Law, Delhi University'],
    admissionProcess: 'Admission to top National Law Universities (NLUs) is through the Common Law Admission Test (CLAT). Other universities have their own entrance exams.',
    roadmap: 'Undergraduate Degree -> Law School (JD/LLB) -> Bar Exam -> Associate at a firm -> Partner or Corporate Counsel',
    avgSalary: '₹6 - 20 LPA',
    futureScope: 'Consistent demand with specialization opportunities in tech, environmental, and corporate law.',
  },
  {
    id: '9',
    slug: 'graphic-designer',
    title: 'Graphic Designer',
    stream: 'Arts',
    description: 'Create visual concepts to communicate ideas that inspire, inform, or captivate consumers.',
    longDescription: 'Graphic designers create visual concepts, using computer software or by hand, to communicate ideas that inspire, inform, and captivate consumers. They develop the overall layout and production design for applications such as advertisements, brochures, magazines, and reports.',
    skills: ['Adobe Creative Suite', 'Typography', 'Color Theory', 'Layout Design'],
    courses: ['B.Des in Graphic Design', 'Diploma in Graphic Design', 'Online Design Courses'],
    exams: ['UCEED', 'NID DAT'],
    topColleges: ['National Institute of Design (NID)', 'IDC School of Design (IIT Bombay)', 'MIT Institute of Design'],
    admissionProcess: 'Admission is based on entrance exams like UCEED and NID DAT, followed by portfolio reviews and interviews.',
    roadmap: 'Build a Strong Portfolio -> Freelance/Intern -> Junior Designer -> Senior Designer/Art Director',
    avgSalary: '₹3 - 8 LPA',
    futureScope: 'High demand in digital media, advertising, and branding agencies.',
  },
  {
    id: '10',
    slug: 'chartered-accountant',
    title: 'Chartered Accountant',
    stream: 'Commerce',
    description: 'Manage finances, audit accounts, and provide financial advice.',
    longDescription: 'A Chartered Accountant (CA) is a professional who is qualified to work in various fields of business and finance, including auditing, taxation, financial management, and general management. The designation is highly respected and opens doors to a wide range of career opportunities in the corporate world.',
    skills: ['Accounting Standards', 'Taxation Laws', 'Auditing', 'Financial Management', 'Ethical Judgement'],
    courses: ['CA Foundation, Intermediate, Final', 'B.Com as a base degree'],
    exams: ['CA Foundation', 'CA Intermediate', 'CA Final'],
    topColleges: ['The Institute of Chartered Accountants of India (ICAI) is the sole governing body.'],
    admissionProcess: 'A student must pass three levels of exams (Foundation, Intermediate, Final) and complete three years of practical training (articleship).',
    roadmap: 'Clear CA Foundation -> Intermediate -> 3 years of Articleship -> Clear CA Final',
    avgSalary: '₹7 - 20 LPA',
    futureScope: 'Evergreen profession with critical roles in all sectors of the economy.',
  },
  {
    id: '11',
    slug: 'physiotherapist',
    title: 'Physiotherapist',
    stream: 'Science',
    description: 'Help people affected by injury, illness or disability through movement and exercise.',
    longDescription: 'Physiotherapists are healthcare professionals who help patients with physical difficulties resulting from illness, injury, disability, or aging. They use movement and exercise, manual therapy, education, and advice to improve their patients\' quality of life.',
    skills: ['Anatomy & Physiology Knowledge', 'Manual Therapy', 'Patient Assessment', 'Empathy', 'Rehabilitation Planning'],
    courses: ['Bachelor of Physiotherapy (BPT)', 'Master of Physiotherapy (MPT)'],
    topColleges: ['Christian Medical College, Vellore', 'Kasturba Medical College, Manipal', 'Apollo Physiotherapy College, Hyderabad'],
    admissionProcess: 'Admission to BPT courses is usually based on Class 12 marks or university-specific entrance exams.',
    roadmap: 'Bachelor\'s Degree (BPT) -> Internship -> License to practice -> Specialization (MPT) -> Clinical Practice or Research',
    avgSalary: '₹3 - 8 LPA',
    futureScope: 'Growing demand due to an aging population and increasing focus on non-invasive treatment methods.',
  },
  {
    id: '12',
    slug: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    stream: 'Science',
    description: 'Protect computer networks and systems from security threats.',
    longDescription: 'Cybersecurity analysts are on the front lines of protecting an organization\'s digital assets. They monitor networks for security breaches, investigate violations when they occur, and work to close off security vulnerabilities. It\'s a critical role in today\'s digital world.',
    skills: ['Network Security', 'SIEM Tools', 'Threat Analysis', 'Ethical Hacking', 'Cryptography'],
    courses: ['B.Tech in Cybersecurity', 'CompTIA Security+', 'Certified Ethical Hacker (CEH)'],
    topColleges: ['IIT Kanpur', 'IIIT Delhi', 'Amrita Vishwa Vidyapeetham'],
    admissionProcess: 'Admission is typically through engineering entrance exams like JEE for undergraduate courses. Many professionals enter this field through certifications.',
    roadmap: 'IT or CS Degree -> Security Certifications -> SOC Analyst -> Senior Analyst/Security Engineer',
    avgSalary: '₹8 - 20 LPA',
    futureScope: 'Extremely high demand as cyber threats become more sophisticated.',
  },
  {
    id: '13',
    slug: 'product-manager',
    title: 'Product Manager',
    stream: 'Commerce',
    description: 'Guide the success of a product and lead the cross-functional team that is responsible for improving it.',
    longDescription: 'Product Managers are the CEOs of their products. They are responsible for product strategy, vision, and roadmap. They work with engineering, design, marketing, and sales to build and launch products that meet user needs and business goals.',
    skills: ['User Research', 'Roadmap Planning', 'Agile Methodologies', 'Leadership', 'Data Analysis'],
    courses: ['MBA', 'B.Tech/BBA', 'Certified Product Manager (CPM)'],
    exams: ['CAT', 'GMAT (for MBA)'],
    topColleges: ['IIMs (for MBA)', 'ISB Hyderabad', 'SPJIMR Mumbai'],
    admissionProcess: 'Many Product Managers transition from engineering or design roles. An MBA from a top institution is a common entry point.',
    roadmap: 'Experience in a related field (dev, design, marketing) -> Associate PM -> Product Manager -> Senior PM/Director',
    avgSalary: '₹15 - 40 LPA',
    futureScope: 'Very strong. Every tech company needs skilled product managers to drive their growth.',
  },
  {
    id: '14',
    slug: 'content-strategist',
    title: 'Content Strategist',
    stream: 'Arts',
    description: 'Plan, create, and manage content to achieve business goals.',
    longDescription: 'Content strategists are responsible for developing a content plan that aligns with a company\'s business objectives. They oversee content creation, from blogs and videos to social media posts, ensuring it is engaging, consistent, and reaches the right audience.',
    skills: ['SEO', 'Content Writing/Editing', 'Analytics', 'Audience Research', 'Content Management Systems (CMS)'],
    courses: ['BA in Journalism/English/Communications', 'Digital Marketing courses'],
    topColleges: ['Symbiosis Institute of Media & Communication, Pune', 'AJK Mass Communication Research Centre, Delhi', 'Xavier Institute of Communications, Mumbai'],
    admissionProcess: 'Entry is typically through a strong portfolio of writing and content work. A degree in communications or journalism is beneficial.',
    roadmap: 'Writer/Editor Role -> Content Creator -> Content Strategist -> Content Director',
    avgSalary: '₹6 - 15 LPA',
    futureScope: 'High demand as "content is king" in the digital marketing landscape.',
  },
  {
    id: '15',
    slug: 'human-resources-manager',
    title: 'Human Resources Manager',
    stream: 'Commerce',
    description: 'Oversee employee relations, recruitment, and administrative functions of a company.',
    longDescription: 'Human Resources (HR) Managers are vital to any organization. They handle everything from recruiting and onboarding new employees to managing payroll, benefits, and company culture. They ensure the workforce is happy, productive, and compliant with labor laws.',
    skills: ['Communication', 'Conflict Resolution', 'Recruitment', 'Labor Law Knowledge', 'Organizational Skills'],
    courses: ['MBA in HR', 'BBA', 'SHRM Certification'],
    exams: ['CAT', 'XAT (for MBA in HR)'],
    topColleges: ['XLRI Jamshedpur', 'Tata Institute of Social Sciences (TISS), Mumbai', 'IIMs'],
    admissionProcess: 'An MBA in HR is a common route, with admissions based on entrance exams like XAT and CAT, followed by interviews.',
    roadmap: 'HR Assistant/Generalist -> HR Specialist -> HR Manager -> HR Director',
    avgSalary: '₹8 - 20 LPA',
    futureScope: 'Stable and essential role in all industries, with a growing focus on culture and employee well-being.',
  },
  {
    id: '16',
    slug: 'ai-ml-engineer',
    title: 'AI/ML Engineer',
    stream: 'Science',
    description: 'Build and deploy machine learning models and AI-powered solutions.',
    longDescription: 'AI/ML Engineers are specialized software engineers who work with artificial intelligence and machine learning algorithms. They design, build, and productionize ML models to solve business problems, working with large datasets and advanced computational frameworks.',
    skills: ['Python', 'TensorFlow/PyTorch', 'Natural Language Processing (NLP)', 'Computer Vision', 'Big Data Technologies'],
    courses: ['MS in AI/ML', 'B.Tech in AI/Data Science', 'Advanced ML Certifications'],
    exams: ['GATE (for M.Tech)'],
    topColleges: ['IIT Hyderabad', 'IISc Bangalore', 'IIIT Hyderabad', 'IIT Bombay'],
    admissionProcess: 'Admission to top postgraduate programs is through the GATE exam. Strong programming skills and a solid portfolio of projects are crucial.',
    roadmap: 'CS/Data Science Degree -> Projects in AI -> Data Scientist/ML Engineer -> Senior ML Engineer/AI Architect',
    avgSalary: '₹12 - 35 LPA',
    futureScope: 'At the forefront of technological innovation with explosive growth and demand.',
  },
  {
    id: '17',
    slug: 'blockchain-developer',
    title: 'Blockchain Developer',
    stream: 'Science',
    description: 'Develop and implement decentralized applications and smart contracts.',
    longDescription: 'Blockchain Developers specialize in creating applications using blockchain technology. This includes building decentralized applications (dApps), writing smart contracts, and managing the entire lifecycle of a blockchain application, from research and design to deployment and maintenance.',
    skills: ['Solidity/Rust', 'Cryptography', 'Smart Contracts', 'Web3.js/Ethers.js', 'Distributed Systems'],
    courses: ['CS Degree', 'Certified Blockchain Developer courses', 'Hands-on projects'],
    topColleges: ['IIT Kanpur offers specialized courses and research in blockchain technology.'],
    admissionProcess: 'This is an emerging field often pursued after a computer science degree. Certifications and a strong project portfolio are key for entry.',
    roadmap: 'Software Dev Experience -> Learn Blockchain Fundamentals -> Build dApps -> Blockchain Developer -> Lead Architect',
    avgSalary: '₹10 - 30 LPA',
    futureScope: 'High-growth emerging field with applications expanding beyond cryptocurrency to finance, supply chain, and more.',
  },
  {
    id: '18',
    slug: 'cloud-architect',
    title: 'Cloud Architect',
    stream: 'Science',
    description: 'Design and manage an organization\'s cloud computing strategy and infrastructure.',
    longDescription: 'Cloud Architects are responsible for overseeing a company\'s cloud computing strategy. This includes cloud adoption plans, cloud application design, and cloud management and monitoring. They work with stakeholders to ensure the cloud structure is scalable, secure, and cost-effective.',
    skills: ['AWS/Azure/GCP', 'Networking', 'Security', 'Infrastructure as Code (Terraform)', 'DevOps'],
    courses: ['Cloud Certifications (AWS Certified Solutions Architect)', 'IT/CS Degree'],
    topColleges: ['Not a traditional college-based career; heavily relies on professional certifications from AWS, Google, and Microsoft.'],
    admissionProcess: 'Entry is typically through gaining experience as a cloud engineer and obtaining professional-level certifications from cloud providers.',
    roadmap: 'IT Admin/Dev -> Cloud Engineer -> Senior Cloud Engineer -> Cloud Architect',
    avgSalary: '₹18 - 45 LPA',
    futureScope: 'Extremely high demand as nearly all businesses move to the cloud.',
  },
  {
    id: '19',
    slug: 'devops-engineer',
    title: 'DevOps Engineer',
    stream: 'Science',
    description: 'Bridge the gap between software development and IT operations.',
    longDescription: 'A DevOps Engineer introduces processes, tools, and methodologies to balance needs throughout the software development life cycle, from coding and deployment, to maintenance and updates. The goal is to shorten the development lifecycle and provide continuous delivery with high software quality.',
    skills: ['CI/CD (Jenkins, GitLab)', 'Containerization (Docker, Kubernetes)', 'Scripting (Bash, Python)', 'Cloud Platforms'],
    courses: ['B.Tech in CS/IT', 'DevOps Certifications (e.g., Docker Certified Associate)'],
    topColleges: ['Similar to Cloud Architect, this is a certification-driven field rather than a specific college degree.'],
    admissionProcess: 'Most DevOps engineers transition from roles like system administrator or software developer after gaining expertise in automation and cloud tools.',
    roadmap: 'SysAdmin or Developer -> Learn Automation & CI/CD -> DevOps Engineer -> Senior DevOps Engineer',
    avgSalary: '₹10 - 25 LPA',
    futureScope: 'Essential role in modern software development, with demand growing continuously.',
  },
  {
    id: '20',
    slug: 'biomedical-engineer',
    title: 'Biomedical Engineer',
    stream: 'Science',
    description: 'Apply engineering principles to biology and medicine for healthcare purposes.',
    longDescription: 'Biomedical Engineers design and create equipment, devices, computer systems, and software used in healthcare. Their work ranges from developing artificial organs and prosthetics to designing medical imaging systems and creating pharmaceutical drugs.',
    skills: ['Biology & Anatomy', 'Medical Device Design', 'Biomaterials', 'CAD Software', 'Research'],
    courses: ['B.Tech/BE in Biomedical Engineering', 'M.Tech for specialization'],
    exams: ['GATE'],
    topColleges: ['IIT Bombay', 'IIT Madras', 'VIT Vellore', 'Manipal Institute of Technology'],
    admissionProcess: 'Admission is through engineering entrance exams like JEE. For postgraduate studies, GATE is the primary exam.',
    roadmap: 'B.Tech Degree -> Internship -> R&D or Clinical Role -> Specialization (e.g., in biomechanics)',
    avgSalary: '₹5 - 12 LPA',
    futureScope: 'Strong growth due to advances in medical technology and an aging population.',
  },
  {
    id: '21',
    slug: 'environmental-scientist',
    title: 'Environmental Scientist',
    stream: 'Science',
    description: 'Use knowledge of the natural sciences to protect the environment and human health.',
    longDescription: 'Environmental Scientists identify, control, or eliminate sources of pollutants or hazards affecting the environment or public health. They analyze environmental problems and develop solutions, working in both field and lab settings.',
    skills: ['Data Collection & Analysis', 'Environmental Regulations', 'GIS Software', 'Field Research', 'Chemistry/Biology'],
    courses: ['BS in Environmental Science/Engineering', 'MS for advanced roles'],
    topColleges: ['TERI School of Advanced Studies, Delhi', 'Indian Institute of Forest Management, Bhopal', 'Delhi Technological University (DTU)'],
    admissionProcess: 'Entry to undergraduate programs is often based on Class 12 science marks. Postgraduate entry may require entrance exams like GATE.',
    roadmap: 'Science Degree -> Fieldwork/Internship -> Environmental Scientist/Consultant -> Policy Advisor',
    avgSalary: '₹4 - 10 LPA',
    futureScope: 'Growing importance and demand due to climate change and sustainability initiatives.',
  },
  {
    id: '22',
    slug: 'game-developer',
    title: 'Game Developer',
    stream: 'Science',
    description: 'Create and produce video games for various platforms.',
    longDescription: 'Game Developers are creative software developers who design and write the code for video games. They can be involved in various aspects of a game\'s creation, from concept and story writing to coding and programming the game\'s mechanics and physics.',
    skills: ['C++/C#', 'Game Engines (Unity, Unreal)', '3D Math', 'Creativity', 'Problem Solving'],
    courses: ['B.Tech in CS with game dev specialization', 'Specialized game design courses'],
    topColleges: ['Backstage Pass Institute of Gaming and Technology, Hyderabad', 'IIFA Multimedia, Bangalore'],
    admissionProcess: 'Many enter through a standard computer science degree and build a portfolio of personal game projects. Specialized institutes have their own entrance criteria.',
    roadmap: 'Learn a game engine -> Build a portfolio of small games -> Junior Game Dev -> Senior/Lead Developer',
    avgSalary: '₹5 - 18 LPA',
    futureScope: 'Massive, ever-growing entertainment industry with opportunities in indie and AAA studios.',
  },
  {
    id: '23',
    slug: 'investment-banker',
    title: 'Investment Banker',
    stream: 'Commerce',
    description: 'Help corporations and governments raise capital by issuing stocks or bonds.',
    longDescription: 'Investment Bankers are financial advisors to corporations and, in some cases, governments. They help their clients raise money and provide a variety of other financial services, such as advising on mergers and acquisitions (M&A).',
    skills: ['Financial Modeling', 'Valuation', 'Negotiation', 'High-Pressure Work Ethic', 'Networking'],
    courses: ['MBA in Finance', 'Degrees in Finance, Economics, or Accounting'],
    exams: ['CAT', 'GMAT'],
    topColleges: ['IIM Ahmedabad, Bangalore, Calcutta', 'ISB Hyderabad', 'FMS Delhi', 'SRCC (for undergrad)'],
    admissionProcess: 'A common path is an undergraduate degree from a top commerce college followed by an MBA from a premier business school.',
    roadmap: 'Prestigious University -> Internship -> Analyst -> Associate -> VP -> Managing Director',
    avgSalary: '₹15 - 50+ LPA',
    futureScope: 'Highly competitive and cyclical, but extremely lucrative. Tied to market performance.',
  },
  {
    id: '24',
    slug: 'management-consultant',
    title: 'Management Consultant',
    stream: 'Commerce',
    description: 'Help organizations improve their performance and efficiency.',
    longDescription: 'Management Consultants are hired by companies to solve complex business problems, devise strategies, and improve financial and operational health. They work as external advisors, bringing fresh perspectives and analytical rigor.',
    skills: ['Problem Solving', 'Data Analysis', 'Communication', 'Project Management', 'Client Relations'],
    courses: ['MBA from a top business school', 'Any analytical undergraduate degree'],
    exams: ['CAT', 'GMAT'],
    topColleges: ['IIM Ahmedabad, Bangalore, Calcutta', 'ISB Hyderabad', 'IITs (for undergraduate engineering)'],
    admissionProcess: 'Firms often hire from a select list of top-tier engineering and business schools. The process involves rigorous case study interviews.',
    roadmap: 'Top University -> Analyst role -> MBA -> Consultant -> Partner',
    avgSalary: '₹18 - 50 LPA',
    futureScope: 'High demand as companies constantly seek to optimize and adapt. Excellent exit opportunities.',
  },
  {
    id: '25',
    slug: 'supply-chain-manager',
    title: 'Supply Chain Manager',
    stream: 'Commerce',
    description: 'Oversee and manage the overall supply chain and logistics strategy.',
    longDescription: 'Supply Chain Managers are responsible for the entire process of getting a product to the end consumer. This includes overseeing procurement, storage, and shipment of goods, ensuring efficiency and cost-effectiveness from supplier to customer.',
    skills: ['Logistics', 'Inventory Management', 'Negotiation', 'Forecasting', 'ERP Systems'],
    courses: ['Degree in Supply Chain Management or Business', 'APICS Certifications (e.g., CSCP)'],
    topColleges: ['IIMs (specialized programs)', 'NITIE Mumbai (now IIM Mumbai)', 'SPJIMR Mumbai'],
    admissionProcess: 'An MBA in Operations or Supply Chain Management is a strong entry point. Admissions are through exams like CAT.',
    roadmap: 'Entry-level logistics role -> Analyst -> Supply Chain Manager -> Director of Operations',
    avgSalary: '₹12 - 30 LPA',
    futureScope: 'Critically important field, especially with the growth of global e-commerce. High demand.',
  },
  {
    id: '26',
    slug: 'actuary',
    title: 'Actuary',
    stream: 'Commerce',
    description: 'Use mathematics and statistics to assess risk in insurance, finance, and other industries.',
    longDescription: 'Actuaries are business professionals who analyze the financial consequences of risk. They use mathematics, statistics, and financial theory to study uncertain future events, especially those of concern to insurance and pension programs.',
    skills: ['Advanced Mathematics & Statistics', 'Probability', 'Financial Theory', 'Risk Analysis', 'Programming'],
    courses: ['Degree in Actuarial Science, Math, or Statistics', 'Series of professional exams'],
    exams: ['ACET (Actuarial Common Entrance Test)'],
    topColleges: ['Institute of Actuaries of India (IAI) governs the profession. Colleges like Christ University have good programs.'],
    admissionProcess: 'Pass the ACET exam to become a student member of IAI, then clear a series of 15 papers to become a qualified actuary.',
    roadmap: 'Degree -> Pass initial actuarial exams -> Entry-level job -> Continue exams to become a fellow',
    avgSalary: '₹10 - 25 LPA',
    futureScope: 'Highly respected and stable profession with excellent compensation and work-life balance.',
  },
  {
    id: '27',
    slug: 'market-research-analyst',
    title: 'Market Research Analyst',
    stream: 'Commerce',
    description: 'Study market conditions to examine potential sales of a product or service.',
    longDescription: 'Market Research Analysts help companies understand what products people want, who will buy them, and at what price. They gather data on consumers and competitors and analyze it to inform marketing strategies and product development.',
    skills: ['Data Analysis', 'Statistics (SPSS/R)', 'Surveys', 'Communication', 'Critical Thinking'],
    courses: ['Degree in Marketing, Business, or Statistics', 'Certifications in market research'],
    topColleges: ['MICA Ahmedabad', 'Delhi School of Economics', 'IIMs'],
    admissionProcess: 'An MBA or a Master\'s in Economics/Statistics is a strong path. Admission is through relevant entrance exams.',
    roadmap: 'Bachelor\'s Degree -> Junior Analyst -> Market Research Analyst -> Research Manager',
    avgSalary: '₹5 - 12 LPA',
    futureScope: 'Solid demand as data-driven decision making becomes more critical for businesses.',
  },
  {
    id: '28',
    slug: 'public-relations-specialist',
    title: 'Public Relations Specialist',
    stream: 'Arts',
    description: 'Craft and maintain a positive public image for a company or organization.',
    longDescription: 'Public Relations (PR) Specialists manage the spread of information between an individual or an organization and the public. They draft press releases, connect with media, and work to build a positive reputation for their clients.',
    skills: ['Writing & Communication', 'Media Relations', 'Crisis Management', 'Social Media', 'Storytelling'],
    courses: ['BA in Communications, Journalism, or Public Relations'],
    topColleges: ['Symbiosis Institute of Media & Communication, Pune', 'Xavier Institute of Communications, Mumbai', 'Indian Institute of Mass Communication (IIMC), Delhi'],
    admissionProcess: 'Admission to top mass communication institutes is through their specific entrance exams and interviews.',
    roadmap: 'PR Internship/Assistant -> PR Coordinator -> PR Specialist -> PR Manager',
    avgSalary: '₹4 - 10 LPA',
    futureScope: 'Ever-evolving field with strong demand in the digital age.',
  },
  {
    id: '29',
    slug: 'animator',
    title: 'Animator',
    stream: 'Arts',
    description: 'Create animation and visual effects for films, video games, television, etc.',
    longDescription: 'Animators produce images that appear to move, known as animation. They create these images for a variety of media, including films, television, video games, and websites. Their work can be 2D, 3D, or stop-motion.',
    skills: ['Maya/Blender', 'Adobe After Effects', 'Drawing', 'Timing and Spacing', 'Creativity'],
    courses: ['BFA in Animation', 'Online animation schools (e.g., Animation Mentor)'],
    topColleges: ['National Institute of Design (NID)', 'IDC School of Design (IIT Bombay)', 'Arena Animation'],
    admissionProcess: 'Entry is through design entrance exams like NID DAT or UCEED, which require a strong portfolio.',
    roadmap: 'Develop a strong demo reel -> Junior Animator -> Animator -> Senior/Lead Animator',
    avgSalary: '₹4 - 12 LPA',
    futureScope: 'Growing demand in entertainment, advertising, and even educational content.',
  },
  {
    id: '30',
    slug: 'journalist',
    title: 'Journalist',
    stream: 'Arts',
    description: 'Research, write, and present news stories and articles.',
    longDescription: 'Journalists inform the public about news and events. They can work for newspapers, magazines, websites, television, or radio. The role involves investigating stories, conducting interviews, and reporting findings in a clear and unbiased way.',
    skills: ['Writing & Editing', 'Interviewing', 'Research', 'Ethics', 'Multimedia Storytelling'],
    courses: ['BA in Journalism or Communications'],
    topColleges: ['Indian Institute of Mass Communication (IIMC), Delhi', 'AJK Mass Communication Research Centre, Delhi', 'Symbiosis Institute of Media & Communication, Pune'],
    admissionProcess: 'Top institutes have their own entrance examinations, which include written tests and interviews.',
    roadmap: 'Work for student paper -> Internship -> Reporter -> Editor/Anchor',
    avgSalary: '₹3 - 9 LPA',
    futureScope: 'Challenging but essential field. Digital media provides new opportunities.',
  },
  {
    id: '31',
    slug: 'historian',
    title: 'Historian',
    stream: 'Arts',
    description: 'Research, analyze, interpret, and write about the past.',
    longDescription: 'Historians study the past by examining written records, physical artifacts, and other sources. They work in museums, archives, historical societies, and government agencies, as well as in academia, to preserve and interpret history for future generations.',
    skills: ['Research', 'Critical Thinking', 'Writing', 'Archival Skills', 'Analysis of primary sources'],
    courses: ['MA or PhD in History is often required'],
    topColleges: ['Jawaharlal Nehru University (JNU), Delhi', 'Delhi University', 'University of Hyderabad'],
    admissionProcess: 'Admission to postgraduate history programs is through university-specific entrance exams that test subject knowledge.',
    roadmap: 'BA in History -> MA/PhD -> Archivist/Curator/Professor',
    avgSalary: '₹5 - 12 LPA',
    futureScope: 'Niche field, with roles in academia, government, and cultural institutions.',
  },
  {
    id: '32',
    slug: 'industrial-designer',
    title: 'Industrial Designer',
    stream: 'Arts',
    description: 'Develop the concepts for manufactured products, such as cars, home appliances, and toys.',
    longDescription: 'Industrial Designers combine art, business, and engineering to develop the concepts for products. They focus on the user experience, aesthetics, and functionality of items we use every day.',
    skills: ['Sketching & 3D Modeling (CAD)', 'Prototyping', 'Material Knowledge', 'User-Centric Design', 'Problem Solving'],
    courses: ['Bachelor of Industrial Design (BID)'],
    exams: ['UCEED', 'NID DAT'],
    topColleges: ['National Institute of Design (NID)', 'IDC School of Design (IIT Bombay)', 'MIT Institute of Design'],
    admissionProcess: 'Admission is via design entrance exams (NID DAT, UCEED) which include aptitude tests, drawing tests, and portfolio reviews.',
    roadmap: 'Design Degree -> Portfolio -> Junior Designer -> Senior Designer -> Design Director',
    avgSalary: '₹6 - 18 LPA',
    futureScope: 'Stable demand, evolving with new technologies like 3D printing and sustainable materials.',
  },
  {
    id: '33',
    slug: 'fashion-designer',
    title: 'Fashion Designer',
    stream: 'Arts',
    description: 'Create original clothing, accessories, and footwear.',
    longDescription: 'Fashion Designers are the creative minds behind clothing and accessories. They sketch designs, select fabrics and patterns, and give instructions on how to make the products they designed.',
    skills: ['Drawing/Sketching', 'Sewing & Pattern Making', 'Fabric Knowledge', 'Trend Awareness', 'Creativity'],
    courses: ['Degree in Fashion Design from a reputable institute (e.g., NIFT, Parsons)'],
    exams: ['NIFT Entrance Exam', 'NID DAT'],
    topColleges: ['National Institute of Fashion Technology (NIFT)', 'Pearl Academy', 'National Institute of Design (NID)'],
    admissionProcess: 'Admission to top fashion schools is highly competitive, based on entrance exams that test creativity, drawing skills, and general aptitude.',
    roadmap: 'Fashion School -> Internship -> Assistant Designer -> Designer -> Head of a brand',
    avgSalary: '₹4 - 15+ LPA',
    futureScope: 'Highly competitive, but with global opportunities and the rise of sustainable fashion.',
  },
  {
    id: '34',
    slug: 'dietitian-nutritionist',
    title: 'Dietitian/Nutritionist',
    stream: 'Science',
    description: 'Advise people on what to eat in order to lead a healthy lifestyle or achieve a specific health-related goal.',
    longDescription: 'Registered Dietitians (RDs) and Nutritionists are experts in food and nutrition. They help promote health and manage disease by creating personalized eating plans for individuals and groups in settings like hospitals, clinics, and private practice.',
    skills: ['Nutritional Science', 'Counseling', 'Biochemistry', 'Meal Planning', 'Empathy'],
    courses: ['BS in Dietetics/Nutrition', 'Completion of a dietetic internship', 'Licensure/Registration exam'],
    topColleges: ['National Institute of Nutrition, Hyderabad', 'Christian Medical College, Vellore', 'University of Delhi'],
    admissionProcess: 'A Bachelor\'s degree in Nutrition is the first step, followed by a postgraduate diploma or Master\'s, and an internship to become a registered dietitian.',
    roadmap: 'Degree & Internship -> Pass RD Exam -> Clinical or Community Nutritionist -> Specialization',
    avgSalary: '₹3 - 7 LPA',
    futureScope: 'Growing demand due to increased public interest in health, wellness, and preventative care.',
  },
  {
    id: '35',
    slug: 'occupational-therapist',
    title: 'Occupational Therapist',
    stream: 'Science',
    description: 'Treat injured, ill, or disabled patients through the therapeutic use of everyday activities.',
    longDescription: 'Occupational Therapists (OTs) help people of all ages participate in the things they want and need to do through the therapeutic use of daily activities (occupations). Common interventions include helping children with disabilities to participate fully in school and social situations, helping people recovering from injury to regain skills, and providing supports for older adults experiencing physical and cognitive changes.',
    skills: ['Patient Care', 'Therapeutic Exercises', 'Rehabilitation', 'Empathy', 'Problem Solving'],
    courses: ['Master\'s or Doctorate in Occupational Therapy'],
    topColleges: ['All India Institute of Physical Medicine and Rehabilitation, Mumbai', 'Christian Medical College, Vellore', 'Manipal University'],
    admissionProcess: 'Admission to a Bachelor of Occupational Therapy (BOT) program is typically based on Class 12 marks or entrance exams. A Master\'s is often required for advanced practice.',
    roadmap: 'Bachelor\'s Degree -> Master\'s/OTD Program -> Pass NBCOT exam -> Licensed OT',
    avgSalary: '₹4 - 9 LPA',
    futureScope: 'Very strong demand, especially with an aging population and in pediatric care.',
  },
  {
    id: '36',
    slug: 'urban-planner',
    title: 'Urban Planner',
    stream: 'Arts',
    description: 'Develop land use plans and programs that help create communities, accommodate population growth, and revitalize physical facilities.',
    longDescription: 'Urban Planners decide how communities and cities will use their land. They create plans for new parks, buildings, and roads, considering factors like population growth, environmental impact, and economic development. Their work shapes the environment we live in.',
    skills: ['GIS Software', 'Public Policy', 'Community Engagement', 'Data Analysis', 'Project Management'],
    courses: ['Master\'s in Urban Planning (MUP)'],
    topColleges: ['School of Planning and Architecture (SPA), Delhi', 'CEPT University, Ahmedabad', 'IIT Kharagpur'],
    admissionProcess: 'A Master\'s in Urban Planning is the standard entry route, with admissions based on undergraduate performance and entrance exams like GATE for some institutes.',
    roadmap: 'Undergrad Degree (Geography, Econ) -> Master\'s Program -> Planner for city/private firm -> Senior Planner',
    avgSalary: '₹6 - 15 LPA',
    futureScope: 'Growing need for sustainable and smart city development drives demand for this role.',
  },
  {
    id: '37',
    slug: 'veterinarian',
    title: 'Veterinarian',
    stream: 'Science',
    description: 'Care for the health of animals. They diagnose, treat, and research medical conditions of pets, livestock, and other animals.',
    longDescription: 'Veterinarians play a major role in the healthcare of animals. They provide services ranging from routine check-ups and vaccinations to complex surgical procedures. They work in private clinics, zoos, farms, and research labs.',
    skills: ['Animal Biology & Anatomy', 'Surgical Skills', 'Diagnostic Abilities', 'Empathy (for animals and owners)', 'Communication'],
    courses: ['Doctor of Veterinary Medicine (DVM)'],
    exams: ['NEET (for BVSc & AH courses)'],
    topColleges: ['Indian Veterinary Research Institute (IVRI), Bareilly', 'Madras Veterinary College, Chennai', 'Anand Agricultural University, Gujarat'],
    admissionProcess: 'Admission to the Bachelor of Veterinary Science & Animal Husbandry (BVSc & AH) course is through the NEET exam in many states.',
    roadmap: 'Bachelor\'s Degree -> Veterinary School (4 years) -> Pass NAVLE exam -> Licensed Veterinarian',
    avgSalary: '₹5 - 12 LPA',
    futureScope: 'Consistent demand as pet ownership and spending on pet care continue to rise.',
  },
  {
    id: '38',
    slug: 'full-stack-developer',
    title: 'Full Stack Developer',
    stream: 'Science',
    description: 'Work on both the front-end (client-side) and back-end (server-side) of a web application.',
    longDescription: 'Full Stack Developers have a broad skillset that allows them to build a complete web application from start to finish. They are proficient in front-end technologies like HTML, CSS, and JavaScript frameworks (React, Angular), as well as back-end technologies like Node.js, Python, or Java and databases (SQL, NoSQL).',
    skills: ['HTML/CSS/JS', 'React/Angular/Vue', 'Node.js/Python/Java', 'Databases (SQL, MongoDB)', 'Git'],
    courses: ['B.Tech in CS', 'Coding Bootcamps'],
    topColleges: ['IITs, NITs, IIITs, and top private universities for a strong CS foundation.'],
    admissionProcess: 'A computer science degree from a top engineering college (via JEE) is a strong foundation. Many also enter the field through intensive coding bootcamps and self-study.',
    roadmap: 'Learn front-end -> Learn back-end -> Build full-stack projects -> Junior Full Stack Dev -> Senior Developer',
    avgSalary: '₹7 - 22 LPA',
    futureScope: 'Extremely versatile and in high demand, especially in startups and smaller companies.',
  },
  {
    id: '39',
    slug: 'data-engineer',
    title: 'Data Engineer',
    stream: 'Science',
    description: 'Build and maintain the infrastructure and pipelines that allow data scientists to work.',
    longDescription: 'Data Engineers are responsible for creating and maintaining the data architecture of a company. They build data pipelines that collect, transform, and store data from various sources, making it accessible for data scientists and analysts to use.',
    skills: ['ETL Processes', 'Big Data (Spark, Hadoop)', 'SQL/NoSQL Databases', 'Python/Scala/Java', 'Cloud Platforms'],
    courses: ['B.Tech in CS/IT', 'Certifications in Big Data technologies'],
    topColleges: ['IITs and NITs provide the necessary computer science fundamentals. Certifications are key.'],
    admissionProcess: 'Entry is typically after a few years of experience as a software engineer or database administrator, followed by specialization and certifications in big data tools.',
    roadmap: 'Software Eng/DBA background -> Learn ETL & Big Data tools -> Data Engineer -> Senior Data Engineer/Architect',
    avgSalary: '₹10 - 30 LPA',
    futureScope: 'Foundation of any data-driven organization. Very high demand as companies scale their data operations.',
  },
  {
    id: '40',
    slug: 'business-development-manager',
    title: 'Business Development Manager',
    stream: 'Commerce',
    description: 'Identify new business opportunities in order to generate revenue, improve profitability and help the business grow.',
    longDescription: 'Business Development Managers are responsible for driving business growth. They build relationships with prospective clients, identify new markets and partnerships, and work to increase revenue. It\'s a strategic role that combines sales, marketing, and strategy.',
    skills: ['Sales & Negotiation', 'Networking', 'Strategic Planning', 'Communication', 'Market Analysis'],
    courses: ['BBA or MBA'],
    topColleges: ['IIMs', 'FMS Delhi', 'NMIMS Mumbai'],
    admissionProcess: 'An MBA is a very common route. Entry is through exams like CAT and is followed by interviews. Strong communication skills are essential.',
    roadmap: 'Sales or Marketing role -> Business Development Executive -> Business Development Manager -> Head of Biz Dev',
    avgSalary: '₹8 - 25 LPA',
    futureScope: 'Crucial role for any company looking to expand. Strong demand across all industries.',
  },
  {
    id: '41',
    slug: 'social-media-manager',
    title: 'Social Media Manager',
    stream: 'Arts',
    description: 'Responsible for a company’s social media marketing and advertising.',
    longDescription: 'Social Media Managers create and manage content for a brand\'s social media profiles, monitor engagement, analyze data, and run social media ad campaigns. They are the voice of the brand online and work to build a community around it.',
    skills: ['Content Creation', 'Social Media Platforms (Instagram, TikTok, etc.)', 'Analytics', 'Copywriting', 'Community Management'],
    courses: ['Degree in Marketing/Communications', 'Digital Marketing certifications'],
    topColleges: ['MICA Ahmedabad', 'Symbiosis Institute of Media & Communication, Pune', 'Many professionals build skills through online courses and practical experience.'],
    admissionProcess: 'A degree in a related field is helpful, but a strong portfolio demonstrating successful social media campaigns is often more important.',
    roadmap: 'Personal projects/Internship -> Social Media Coordinator -> Social Media Manager -> Head of Social',
    avgSalary: '₹4 - 10 LPA',
    futureScope: 'Essential for modern marketing. The field is constantly evolving with new platforms and trends.',
  },
  {
    id: '42',
    slug: 'event-manager',
    title: 'Event Manager',
    stream: 'Commerce',
    description: 'Plan and execute events, taking responsibility for the creative, technical, and logistical elements.',
    longDescription: 'Event Managers organize and oversee events of all kinds, from conferences and corporate meetings to weddings and festivals. They handle every detail, including budgeting, scheduling, venue selection, and coordinating with vendors.',
    skills: ['Organization', 'Budgeting', 'Vendor Management', 'Problem Solving', 'Communication'],
    courses: ['Degree in Hospitality, Marketing, or Communications'],
    topColleges: ['National Institute of Event Management (NIEM)', 'Amity Institute of Event Management', 'Indian School of Business (for MBA)'],
    admissionProcess: 'Specialized diplomas and degrees in event management are available. A background in hospitality or marketing is also very useful.',
    roadmap: 'Event Assistant/Coordinator -> Event Planner/Manager -> Senior Event Manager',
    avgSalary: '₹4 - 12 LPA',
    futureScope: 'Demand is recovering post-pandemic, with a growing focus on hybrid and virtual events.',
  },
  {
    id: '43',
    slug: 'film-director',
    title: 'Film Director',
    stream: 'Arts',
    description: 'Control a film\'s artistic and dramatic aspects and visualizes the screenplay.',
    longDescription: 'The Film Director is the creative leader of a film production. They are responsible for interpreting the script, guiding the actors, and overseeing the work of the entire crew to bring their creative vision to the screen.',
    skills: ['Storytelling', 'Leadership', 'Visual Composition', 'Communication', 'Knowledge of all aspects of filmmaking'],
    courses: ['Film School (e.g., FTII, NYU Tisch)', 'Hands-on experience'],
    topColleges: ['Film and Television Institute of India (FTII), Pune', 'Satyajit Ray Film and Television Institute, Kolkata', 'Whistling Woods International, Mumbai'],
    admissionProcess: 'Admission to top film schools is extremely competitive and involves a rigorous selection process including interviews and portfolio submission.',
    roadmap: 'Make short films -> Work on film sets (any role) -> Direct independent films -> Direct studio films',
    avgSalary: 'Highly variable',
    futureScope: 'Extremely competitive. The rise of streaming platforms has created more opportunities.',
  },
  {
    id: '44',
    slug: 'technical-writer',
    title: 'Technical Writer',
    stream: 'Arts',
    description: 'Prepare instruction manuals, journal articles, and other supporting documents to communicate complex information.',
    longDescription: 'Technical Writers take complex, technical information and translate it into easily understandable content for a specific audience. They create user manuals, API documentation, how-to guides, and more, for software, hardware, and other products.',
    skills: ['Clear Writing', 'Ability to understand complex topics', 'Audience Analysis', 'Documentation Tools (e.g., MadCap Flare)', 'Attention to Detail'],
    courses: ['Degree in English, Communications, or a technical field'],
    topColleges: ['No specific colleges; a strong writing portfolio is key. A degree in English or Journalism from colleges like St. Stephen\'s or Lady Shri Ram is a good start.'],
    admissionProcess: 'Employers look for excellent writing samples and the ability to grasp technical concepts. A background in a technical field is a plus.',
    roadmap: 'Degree -> Internship -> Junior Technical Writer -> Senior Technical Writer/Documentation Manager',
    avgSalary: '₹5 - 15 LPA',
    futureScope: 'Strong and steady demand in the tech, medical, and engineering industries.',
  },
  {
    id: '45',
    slug: 'interior-designer',
    title: 'Interior Designer',
    stream: 'Arts',
    description: 'Make interior spaces functional, safe, and beautiful by determining space requirements and selecting decorative items.',
    longDescription: 'Interior Designers plan and design the spaces inside buildings. This includes selecting color schemes, furniture, lighting, and materials. They must be able to draw, read blueprints, and understand building codes.',
    skills: ['Space Planning', 'Color Theory', 'CAD Software', 'Project Management', 'Client Communication'],
    courses: ['Degree in Interior Design'],
    topColleges: ['National Institute of Design (NID)', 'CEPT University, Ahmedabad', 'Sir J.J. School of Art, Mumbai'],
    admissionProcess: 'Admission to top design schools is through entrance exams like NID DAT and portfolio reviews.',
    roadmap: 'Design School -> Internship -> Junior Designer -> Senior Designer/Own a firm',
    avgSalary: '₹3 - 10 LPA',
    futureScope: 'Demand tied to real estate and construction. Growing interest in sustainable and smart home design.',
  },
  {
    id: '46',
    slug: 'speech-language-pathologist',
    title: 'Speech-Language Pathologist',
    stream: 'Science',
    description: 'Assess, diagnose, treat, and help to prevent communication and swallowing disorders.',
    longDescription: 'Speech-Language Pathologists (SLPs) work with people of all ages who have difficulties with speech, language, voice, fluency (stuttering), or swallowing. They work in schools, hospitals, and private practices.',
    skills: ['Phonetics & Linguistics', 'Patient Assessment', 'Therapy Techniques', 'Empathy', 'Patience'],
    courses: ['Master\'s Degree in Speech-Language Pathology'],
    topColleges: ['All India Institute of Speech and Hearing (AIISH), Mysore', 'Christian Medical College, Vellore', 'Manipal University'],
    admissionProcess: 'Requires a Bachelor\'s in Audiology and Speech-Language Pathology (BASLP) followed by a Master\'s degree. Admission is through university-specific entrance exams.',
    roadmap: 'Bachelor\'s Degree -> Master\'s Program -> Clinical Fellowship -> Pass Praxis exam for ASHA certification',
    avgSalary: '₹4 - 8 LPA',
    futureScope: 'Excellent job outlook due to growing awareness and an aging population.',
  },
  {
    id: '47',
    slug: 'public-policy-analyst',
    title: 'Public Policy Analyst',
    stream: 'Arts',
    description: 'Examine the effectiveness of existing policies and lay out the potential impacts of new ones.',
    longDescription: 'Public Policy Analysts research issues, analyze data, and advise policymakers on the best course of action. They work for government agencies, think tanks, and non-profit organizations to influence and shape public policy on issues like healthcare, education, and the environment.',
    skills: ['Research & Analysis', 'Statistics', 'Economics', 'Writing', 'Public Speaking'],
    courses: ['Master\'s in Public Policy (MPP) or Public Administration (MPA)'],
    exams: ['UPSC Civil Services (for government roles)'],
    topColleges: ['Jindal School of Government and Public Policy', 'Tata Institute of Social Sciences (TISS)', 'IIM Bangalore (PGPPM)'],
    admissionProcess: 'A Master\'s degree is usually required. Admission is based on undergraduate records and entrance exams specific to the institute.',
    roadmap: 'Bachelor\'s Degree -> Master\'s Program -> Policy Analyst -> Senior Analyst/Policy Director',
    avgSalary: '₹6 - 15 LPA',
    futureScope: 'Important role in governance and advocacy, with opportunities in various sectors.',
  },
  {
    id: '48',
    slug: 'translator-interpreter',
    title: 'Translator/Interpreter',
    stream: 'Arts',
    description: 'Convert information from one language into another.',
    longDescription: 'Translators work with written text, while interpreters work with spoken language. Both require fluency in at least two languages and a deep understanding of the corresponding cultures. They work in various settings, including international business, diplomacy, healthcare, and legal proceedings.',
    skills: ['Fluency in multiple languages', 'Cultural knowledge', 'Excellent listening/reading and writing skills', 'Specialized vocabulary (e.g., legal, medical)'],
    courses: ['Bachelor\'s degree in the language', 'Certification from organizations like the ATA'],
    topColleges: ['Jawaharlal Nehru University (JNU), Delhi', 'University of Delhi', 'English and Foreign Languages University, Hyderabad'],
    admissionProcess: 'A degree in a specific language is the best starting point. Professional certification can greatly enhance job prospects.',
    roadmap: 'Become fluent -> Get certified -> Freelance or work for an agency -> Specialize in a field',
    avgSalary: '₹3 - 10 LPA',
    futureScope: 'Good demand in a globalized world, especially for less common languages and specialized fields.',
  },
  {
    id: '49',
    slug: 'school-counselor',
    title: 'School Counselor',
    stream: 'Arts',
    description: 'Help students develop the academic and social skills they need to succeed in school and in life.',
    longDescription: 'School Counselors work with students at all levels, from elementary to high school. They provide guidance on academic planning, career exploration, and personal challenges. They are a key support system for students\' mental and emotional well-being.',
    skills: ['Counseling', 'Child Development', 'Active Listening', 'Empathy', 'Knowledge of academic/career paths'],
    courses: ['Master\'s in School Counseling'],
    topColleges: ['Tata Institute of Social Sciences (TISS)', 'University of Delhi', 'NCERT (offers a diploma course)'],
    admissionProcess: 'A Master\'s degree in Psychology or Counseling is required, often followed by a B.Ed. for school positions.',
    roadmap: 'Bachelor\'s Degree -> Master\'s Program -> State Licensure/Certification -> School Counselor',
    avgSalary: '₹4 - 8 LPA',
    futureScope: 'Growing recognition of the importance of mental health in schools is increasing demand.',
  },
  {
    id: '50',
    slug: 'renewable-energy-technician',
    title: 'Renewable Energy Technician',
    stream: 'Science',
    description: 'Install, maintain, and repair renewable energy systems, such as solar panels and wind turbines.',
    longDescription: 'As the world shifts towards sustainable energy, Renewable Energy Technicians are in high demand. They are responsible for the hands-on work of setting up and maintaining the equipment that generates clean power.',
    skills: ['Mechanical & Electrical Skills', 'Troubleshooting', 'Safety Procedures', 'Blueprint Reading'],
    courses: ['Associate\'s degree or vocational training in renewable energy'],
    topColleges: ['National Institute of Solar Energy (NISE)', 'National Institute of Wind Energy (NIWE)', 'Various ITIs and polytechnics offer relevant courses.'],
    admissionProcess: 'Entry is often through vocational training programs or diplomas in electrical or mechanical engineering.',
    roadmap: 'Technical School/Associate\'s Degree -> Apprenticeship/Entry-level Technician -> Senior Technician/Site Manager',
    avgSalary: '₹4 - 9 LPA',
    futureScope: 'One of the fastest-growing job sectors globally due to the push for clean energy.',
  },
  {
    id: '51',
    slug: 'e-commerce-manager',
    title: 'E-commerce Manager',
    stream: 'Commerce',
    description: 'Oversee a company’s online sales strategy and operations.',
    longDescription: 'E-commerce Managers are responsible for the entire online shopping experience. They manage the company website, online marketing, customer service, order fulfillment, and analyze data to increase online sales and profitability.',
    skills: ['Digital Marketing (SEO, SEM)', 'Platform knowledge (Shopify, Magento)', 'Web Analytics', 'Conversion Rate Optimization (CRO)', 'Project Management'],
    courses: ['Degree in Business or Marketing', 'Experience in digital marketing'],
    topColleges: ['IIMs', 'MICA Ahmedabad', 'NMIMS Mumbai'],
    admissionProcess: 'An MBA in Marketing or a strong background in digital marketing is a common entry point.',
    roadmap: 'Digital Marketing role -> E-commerce Specialist -> E-commerce Manager -> Director of E-commerce',
    avgSalary: '₹8 - 20 LPA',
    futureScope: 'Extremely high demand as retail continues to shift online.',
  },
  {
    id: '52',
    slug: 'geologist',
    title: 'Geologist',
    stream: 'Science',
    description: 'Study the Earth\'s physical structure, substance, history, and the processes which act on them.',
    longDescription: 'Geologists study the materials, processes, products, physical nature, and history of the Earth. They work in industries like oil and gas exploration, mining, environmental consulting, and for government agencies.',
    skills: ['Rock & Mineral Identification', 'Field Mapping', 'Data Analysis', 'GIS', 'Geophysics'],
    courses: ['BS in Geology', 'MS or PhD for research or specialized roles'],
    topColleges: ['IIT Kharagpur', 'University of Delhi', 'Indian School of Mines (ISM), Dhanbad', 'Banaras Hindu University (BHU)'],
    admissionProcess: 'Admission to undergraduate courses is often through university entrance tests. For postgraduate, GATE or university-specific exams are held.',
    roadmap: 'Geology Degree -> Field Assistant -> Geologist -> Senior Geologist/Project Manager',
    avgSalary: '₹6 - 18 LPA',
    futureScope: 'Demand is tied to the energy and resource sectors, with growing opportunities in environmental geology.',
  },
  {
    id: '53',
    slug: 'forensic-scientist',
    title: 'Forensic Scientist',
    stream: 'Science',
    description: 'Collect and analyze evidence from crime scenes to help solve criminal cases.',
    longDescription: 'Forensic Scientists are crucial to the criminal justice system. They work in labs to analyze DNA, fibers, chemicals, and other evidence found at crime scenes. Their work must be precise and methodical to stand up in court.',
    skills: ['Attention to Detail', 'Analytical Chemistry', 'Biology (DNA Analysis)', 'Lab Procedures', 'Integrity'],
    courses: ['Degree in a natural science (Chemistry, Biology) with a forensic specialization'],
    topColleges: ['Lok Nayak Jayaprakash Narayan National Institute of Criminology & Forensic Science (LNJN NICFS), Delhi', 'Gujarat Forensic Sciences University (GFSU)', 'Osmania University, Hyderabad'],
    admissionProcess: 'A Bachelor\'s degree in a core science is required, followed by a Master\'s in Forensic Science. Admission is through university entrance exams.',
    roadmap: 'Science Degree -> Lab Technician -> Forensic Scientist -> Crime Lab Supervisor',
    avgSalary: '₹4 - 10 LPA',
    futureScope: 'Stable demand in law enforcement and government agencies.',
  },
  {
    id: '54',
    slug: 'paramedic',
    title: 'Paramedic',
    stream: 'Science',
    description: 'Provide emergency medical care to people who are sick or injured.',
    longDescription: 'Paramedics are highly trained first responders who provide advanced medical care in emergency situations. They are often the first healthcare professionals on the scene of an accident or medical crisis, making life-or-death decisions under pressure.',
    skills: ['Emergency Medical Procedures', 'Quick Thinking', 'Calm under pressure', 'Physical Stamina', 'Communication'],
    courses: ['Paramedic certification program (often an Associate\'s degree)'],
    topColleges: ['Christian Medical College, Vellore', 'All India Institute of Medical Sciences (AIIMS)', 'Apollo Hospitals Educational and Research Foundation'],
    admissionProcess: 'Various diploma and degree courses are available. Admission is typically based on Class 12 Science marks.',
    roadmap: 'EMT-Basic training -> Paramedic Program -> National Registry certification -> Paramedic',
    avgSalary: '₹3 - 7 LPA',
    futureScope: 'Consistent and growing demand for emergency medical services nationwide.',
  },
  {
    id: '55',
    slug: 'curator',
    title: 'Curator',
    stream: 'Arts',
    description: 'Acquire, care for, and develop a collection of artifacts or artworks for a museum or gallery.',
    longDescription: 'Curators are the content specialists of cultural institutions. They are responsible for assembling, managing, and presenting collections of historical artifacts or artworks. This involves research, acquisition, and creating exhibitions to engage the public.',
    skills: ['Subject Matter Expertise', 'Research', 'Writing', 'Project Management', 'Public Speaking'],
    courses: ['Master\'s or PhD in a relevant field (e.g., Art History, History, Archaeology)'],
    topColleges: ['National Museum Institute of History of Art, Conservation and Museology, Delhi', 'Maharaja Sayajirao University of Baroda', 'JNU'],
    admissionProcess: 'A postgraduate degree in a relevant discipline like Art History or Museology is essential. Admission is through university entrance exams and interviews.',
    roadmap: 'Relevant advanced degree -> Internship/Assistant role -> Assistant Curator -> Curator -> Chief Curator',
    avgSalary: '₹4 - 10 LPA',
    futureScope: 'Competitive field, but essential for cultural and historical preservation.',
  },
  {
    id: '56',
    slug: 'librarian',
    title: 'Librarian',
    stream: 'Arts',
    description: 'Help people find information and conduct research for personal and professional use.',
    longDescription: 'Modern librarians are information experts. They manage collections of books, journals, and digital resources, and they teach people how to find and evaluate information. They work in public, academic, school, and special libraries.',
    skills: ['Information Organization', 'Research', 'Customer Service', 'Database Management', 'Literacy Promotion'],
    courses: ['Master of Library and Information Science (MLIS)'],
    topColleges: ['University of Delhi', 'Tata Institute of Social Sciences (TISS)', 'Documentation Research and Training Centre (DRTC), Bangalore'],
    admissionProcess: 'A Bachelor\'s degree in any field followed by a Master\'s in Library and Information Science (MLIS) is the standard path. Admission is via university entrance tests.',
    roadmap: 'Bachelor\'s Degree -> MLIS Program -> Librarian -> Department Head/Library Director',
    avgSalary: '₹4 - 9 LPA',
    futureScope: 'The role is evolving with technology, focusing more on digital literacy and community programming.',
  },
  {
    id: '57',
    slug: 'economist',
    title: 'Economist',
    stream: 'Commerce',
    description: 'Study the production and distribution of resources, goods, and services.',
    longDescription: 'Economists analyze data, research trends, and evaluate economic issues for governments, companies, and think tanks. They create forecasts and models to predict the impact of policies, investments, and market changes.',
    skills: ['Statistical Analysis (Econometrics)', 'Economic Theory', 'Data Analysis (Stata/R)', 'Writing', 'Critical Thinking'],
    courses: ['Master\'s or PhD in Economics is typically required'],
    topColleges: ['Delhi School of Economics', 'Indian Statistical Institute (ISI)', 'Indira Gandhi Institute of Development Research (IGIDR), Mumbai'],
    admissionProcess: 'Admission to top Master\'s programs is through rigorous entrance exams testing knowledge of microeconomics, macroeconomics, and econometrics.',
    roadmap: 'Bachelor\'s in Econ -> Master\'s/PhD -> Research Assistant/Analyst -> Economist',
    avgSalary: '₹10 - 25 LPA',
    futureScope: 'Strong demand in government, finance, and consulting for experts who can interpret complex data.',
  },
  {
    id: '58',
    slug: 'pilot',
    title: 'Pilot',
    stream: 'Science',
    description: 'Fly and navigate airplanes, helicopters, and other aircraft.',
    longDescription: 'Airline and commercial pilots transport passengers and cargo on a fixed schedule. It is a highly responsible job that requires extensive training, technical skill, and the ability to remain calm and make clear decisions under pressure.',
    skills: ['Aviation Knowledge', 'Spatial Awareness', 'Communication', 'Problem Solving', 'Attention to Detail'],
    courses: ['Flight School for licenses (PPL, CPL, ATPL)', 'Bachelor\'s degree often preferred by major airlines'],
    topColleges: ['Indira Gandhi Rashtriya Uran Akademi (IGRUA)', 'CAE Oxford Aviation Academy', 'National Flying Training Institute (NFTI)'],
    admissionProcess: 'Aspiring pilots must clear Class 2 and Class 1 medical exams, pass written exams, and complete a minimum number of flying hours at a DGCA-approved flight school.',
    roadmap: 'Flight training to build hours -> Certified Flight Instructor -> Regional Airline Pilot -> Major Airline Pilot',
    avgSalary: '₹12 - 40 LPA',
    futureScope: 'Global demand for pilots is expected to be very high over the next two decades.',
  },
  {
    id: '59',
    slug: 'civil-engineer',
    title: 'Civil Engineer',
    stream: 'Science',
    description: 'Design, build, and maintain the infrastructure of modern society.',
    longDescription: 'Civil Engineers conceive, design, build, supervise, operate, construct, and maintain infrastructure projects and systems in the public and private sector, including roads, buildings, airports, tunnels, dams, bridges, and systems for water supply and sewage treatment.',
    skills: ['AutoCAD', 'Project Management', 'Structural Analysis', 'Physics & Math', 'Problem Solving'],
    courses: ['B.Tech/BE in Civil Engineering', 'Professional Engineer (PE) license'],
    exams: ['GATE', 'ESE (Engineering Services Examination)'],
    topColleges: ['IIT Bombay', 'IIT Delhi', 'IIT Roorkee', 'NIT Trichy'],
    admissionProcess: 'Admission is through JEE Main and JEE Advanced. For government jobs, exams like the Engineering Services Examination (ESE) are required.',
    roadmap: 'Engineering Degree -> Entry-level Engineer (EIT) -> Pass PE exam -> Project Engineer/Manager',
    avgSalary: '₹5 - 15 LPA',
    futureScope: 'Constant demand due to the need to maintain and upgrade aging infrastructure and build new projects.',
  },
  {
    id: '60',
    slug: 'pharmacist',
    title: 'Pharmacist',
    stream: 'Science',
    description: 'Dispense prescription medications to patients and offer expertise in the safe use of prescriptions.',
    longDescription: 'Pharmacists are healthcare professionals who are experts in medication. They dispense drugs prescribed by doctors, advise patients on medication use, and ensure that prescriptions do not interact negatively. They work in retail pharmacies, hospitals, and clinics.',
    skills: ['Pharmacology', 'Chemistry', 'Attention to Detail', 'Patient Counseling', 'Accuracy'],
    courses: ['Doctor of Pharmacy (Pharm.D.)'],
    topColleges: ['National Institute of Pharmaceutical Education and Research (NIPER), Mohali', 'Jamia Hamdard, Delhi', 'Manipal College of Pharmaceutical Sciences'],
    admissionProcess: 'Admission to B.Pharm is based on entrance exams like NEET or university-specific tests. For M.Pharm, GPAT is the main exam.',
    roadmap: 'Pre-pharmacy coursework -> Pharmacy School (Pharm.D.) -> Pass NAPLEX/MPJE exams -> Licensed Pharmacist',
    avgSalary: '₹3 - 7 LPA',
    futureScope: 'Stable demand, with an expanding role in patient care and medication management.',
  },
  {
    id: '61',
    slug: 'psychologist',
    title: 'Psychologist',
    stream: 'Arts',
    description: 'Study mental processes and human behavior by observing, interpreting, and recording how people relate to one another and their environments.',
    longDescription: 'Psychologists diagnose and treat mental, emotional, and behavioral disorders. They use various techniques, including observation, assessment, and experimentation, to develop theories about the feelings and thoughts that influence individuals. They can work in clinical, counseling, or research settings.',
    skills: ['Active Listening', 'Psychological Assessment', 'Therapeutic Techniques', 'Empathy', 'Research'],
    courses: ['PhD or PsyD in Psychology for clinical practice'],
    topColleges: ['National Institute of Mental Health and Neurosciences (NIMHANS), Bangalore', 'Tata Institute of Social Sciences (TISS), Mumbai', 'University of Delhi'],
    admissionProcess: 'A Master\'s degree in Psychology is the minimum requirement for many roles. For clinical practice, an M.Phil or PhD is required, with admission through rigorous entrance exams and interviews.',
    roadmap: 'Bachelor\'s in Psychology -> PhD/PsyD Program -> Internship/Postdoc -> State Licensure -> Practicing Psychologist',
    avgSalary: '₹5 - 15 LPA',
    futureScope: 'Growing demand as awareness of mental health increases.',
  }
];

export const quizQuestions: Question[] = [
  {
    id: 'q_stream',
    category: 'initial',
    text: 'What stream have you studied or are currently studying?',
    options: [
      { text: 'Science', value: 'science' },
      { text: 'Commerce', value: 'commerce' },
      { text: 'Arts / Humanities', value: 'arts' },
    ],
  },
  // Science Questions
  {
    id: 's1',
    category: 'science',
    text: 'Which of these subjects excites you the most?',
    options: [
      { text: 'Physics - understanding the fundamental laws of the universe.', value: 'analytical_physics' },
      { text: 'Biology - exploring the complexities of living organisms.', value: 'caring_bio' },
      { text: 'Computer Science - building applications and solving problems with code.', value: 'technical_cs' },
      { text: 'Chemistry - experimenting with substances and their properties.', value: 'analytical_chem' },
    ],
  },
  {
    id: 's2',
    category: 'science',
    text: 'You are most drawn to...',
    options: [
      { text: 'Designing and building structures or machines.', value: 'technical_design' },
      { text: 'Conducting research and analyzing data to discover new things.', value: 'analytical_research' },
      { text: 'Caring for the health and well-being of others.', value: 'caring_health' },
      { text: 'Using technology to create innovative digital solutions.', value: 'technical_digital' },
    ],
  },
   {
    id: 's3',
    category: 'science',
    text: 'In a hospital setting, would you rather be...',
    options: [
      { text: 'The doctor diagnosing patients.', value: 'caring_doctor' },
      { text: 'The lab technician analyzing samples.', value: 'analytical_lab' },
      { text: 'The therapist helping patients recover movement.', value: 'caring_therapist' },
      { text: 'The engineer maintaining medical equipment.', value: 'technical_medical' },
    ],
  },
  {
    id: 's4',
    category: 'science',
    text: 'What kind of problem-solving do you prefer?',
    options: [
        { text: 'Solving complex logical puzzles with clear answers.', value: 'analytical_logic' },
        { text: 'Finding creative, user-centric solutions to ambiguous problems.', value: 'creative_user' },
        { text: 'Diagnosing and fixing issues in complex systems (like networks or software).', value: 'technical_troubleshoot' },
        { text: 'Developing strategies to protect systems from external threats.', value: 'analytical_security' },
    ],
  },
  {
      id: 's5',
      category: 'science',
      text: 'Your ideal work environment would be...',
      options: [
          { text: 'A fast-paced tech company with a focus on innovation.', value: 'technical_innovation' },
          { text: 'A research lab dedicated to scientific discovery.', value: 'analytical_discovery' },
          { text: 'A healthcare setting, directly interacting with patients.', value: 'caring_patient' },
          { text: 'Out in the field, studying natural environments.', value: 'analytical_field' },
      ],
  },
  {
      id: 's6',
      category: 'science',
      text: 'Which project sounds most interesting?',
      options: [
          { text: 'Building a mobile app from scratch.', value: 'technical_app' },
          { text: 'Developing a new, life-saving medical device.', value: 'caring_device' },
          { text: 'Creating a predictive model based on a large dataset.', value: 'analytical_model' },
          { text: 'Designing a sustainable and eco-friendly building.', value: 'technical_sustainable' },
      ],
  },
  {
      id: 's7',
      category: 'science',
      text: 'I enjoy working with...',
      options: [
          { text: 'Abstract concepts and algorithms.', value: 'analytical_abstract' },
          { text: 'Tangible objects and machinery.', value: 'technical_machinery' },
          { text: 'People and helping them with their problems.', value: 'caring_people' },
          { text: 'Data and finding patterns within it.', value: 'analytical_patterns' },
      ],
  },
  {
      id: 's8',
      category: 'science',
      text: 'When faced with a challenge, your first instinct is to...',
      options: [
          { text: 'Break it down into smaller, logical steps.', value: 'analytical_breakdown' },
          { text: 'Brainstorm creative and unconventional solutions.', value: 'creative_brainstorm' },
          { text: 'Research what has been done before and improve upon it.', value: 'analytical_improve' },
          { text: 'Collaborate with a team to get different perspectives.', value: 'social_collaborate' },
      ],
  },
  {
      id: 's9',
      category: 'science',
      text: 'Which emerging technology excites you the most?',
      options: [
          { text: 'Artificial Intelligence and Machine Learning', value: 'technical_ai' },
          { text: 'Biotechnology and Genetic Engineering', value: 'caring_biotech' },
          { text: 'Renewable Energy and Sustainable Tech', value: 'technical_renewable' },
          { text: 'Blockchain and Decentralized Systems', value: 'analytical_blockchain' },
      ],
  },
  {
      id: 's10',
      category: 'science',
      text: 'A good day at work for you means...',
      options: [
          { text: 'I solved a difficult technical problem.', value: 'technical_solve' },
          { text: 'I made a positive difference in someone\'s life.', value: 'caring_difference' },
          { text: 'I discovered a new insight from data.', value: 'analytical_insight' },
          { text: 'I created something that is both functional and beautiful.', value: 'creative_functional' },
      ],
  },
  {
      id: 's11',
      category: 'science',
      text: 'You are more of a...',
      options: [
          { text: 'Builder, who likes to construct things.', value: 'technical_builder' },
          { text: 'Thinker, who likes to analyze and understand things.', value: 'analytical_thinker' },
          { text: 'Helper, who likes to support and care for others.', value: 'caring_helper' },
          { text: 'Creator, who likes to imagine and design new things.', value: 'creative_creator' },
      ],
  },
  {
      id: 's12',
      category: 'science',
      text: 'What is more important in a career?',
      options: [
          { text: 'Intellectual stimulation and continuous learning.', value: 'analytical_learning' },
          { text: 'Making a tangible impact on the world.', value: 'caring_impact' },
          { text: 'Financial security and career stability.', value: 'business_security' },
          { text: 'Creative freedom and self-expression.', value: 'creative_freedom' },
      ],
  },
  {
      id: 's13',
      category: 'science',
      text: 'Which task would you be most comfortable with?',
      options: [
          { text: 'Writing a detailed scientific report.', value: 'analytical_report' },
          { text: 'Operating complex machinery or lab equipment.', value: 'technical_equipment' },
          { text: 'Comforting a patient or their family.', value: 'caring_comfort' },
          { text: 'Presenting a complex idea to a non-technical audience.', value: 'social_presenting' },
      ],
  },
  {
      id: 's14',
      category: 'science',
      text: 'You prefer tasks that are...',
      options: [
          { text: 'Structured and methodical.', value: 'analytical_structured' },
          { text: 'Hands-on and practical.', value: 'technical_practical' },
          { text: 'Human-centered and empathetic.', value: 'caring_empathetic' },
          { text: 'Open-ended and require imagination.', value: 'creative_imagination' },
      ],
  },
  {
      id: 's15',
      category: 'science',
      text: 'Your dream job involves...',
      options: [
          { text: 'Working at the cutting edge of technology.', value: 'technical_cuttingedge' },
          { text: 'Solving global health problems.', value: 'caring_global' },
          { text: 'Protecting the environment for future generations.', value: 'analytical_environment' },
          { text: 'Exploring the frontiers of space and the universe.', value: 'analytical_space' },
      ],
  },

  // Commerce Questions
  {
    id: 'c1',
    category: 'commerce',
    text: 'What aspect of business interests you the most?',
    options: [
      { text: 'Analyzing financial statements and market trends.', value: 'analytical_finance' },
      { text: 'Developing strategies to promote and sell products.', value: 'business_marketing' },
      { text: 'Managing company finances and ensuring compliance.', value: 'business_management' },
      { text: 'Understanding consumer behavior and market dynamics.', value: 'social_consumer' },
    ],
  },
  {
    id: 'c2',
    category: 'commerce',
    text: 'Your ideal task for the day would be...',
    options: [
      { text: 'Creating a detailed financial model in Excel.', value: 'analytical_excel' },
      { text: 'Designing a creative advertising campaign.', value: 'creative_ad' },
      { text: 'Negotiating a major business deal.', value: 'business_negotiate' },
      { text: 'Auditing company accounts to ensure accuracy.', value: 'analytical_audit' },
    ],
  },
  {
    id: 'c3',
    category: 'commerce',
    text: 'When thinking about a company, you are most curious about...',
    options: [
      { text: 'Its stock performance and valuation.', value: 'analytical_stock' },
      { text: 'Its brand story and customer perception.', value: 'creative_brand' },
      { text: 'Its internal structure and employee satisfaction.', value: 'social_hr' },
      { text: 'Its overall business strategy and market position.', value: 'business_strategy' },
    ],
  },
  {
    id: 'c4',
    category: 'commerce',
    text: 'Which scenario sounds most appealing?',
    options: [
        { text: 'Identifying a new, untapped market for a product.', value: 'business_market' },
        { text: 'Developing a strategy to improve a company\'s profitability.', value: 'analytical_profit' },
        { text: 'Building a strong, positive company culture.', value: 'social_culture' },
        { text: 'Managing the logistics of a global supply chain.', value: 'business_logistics' },
    ],
  },
  {
      id: 'c5',
      category: 'commerce',
      text: 'You are best at...',
      options: [
          { text: 'Persuading others and closing deals.', value: 'social_persuade' },
          { text: 'Spotting patterns and trends in numbers.', value: 'analytical_trends' },
          { text: 'Organizing people and processes efficiently.', value: 'business_organize' },
          { text: 'Coming up with innovative ideas for growth.', value: 'creative_growth' },
      ],
  },
  {
      id: 'c6',
      category: 'commerce',
      text: 'What type of risk are you most comfortable with?',
      options: [
          { text: 'Financial risk, like investing in the stock market.', value: 'analytical_financialrisk' },
          { text: 'Market risk, like launching a new, unproven product.', value: 'business_marketrisk' },
          { text: 'I prefer to minimize risk by ensuring rules and regulations are followed.', value: 'analytical_compliance' },
          { text: 'Strategic risk, like entering a new international market.', value: 'business_strategicrisk' },
      ],
  },
  {
      id: 'c7',
      category: 'commerce',
      text: 'Which department would you want to lead?',
      options: [
          { text: 'Finance or Accounting', value: 'analytical_leadfinance' },
          { text: 'Marketing or Sales', value: 'social_leadsales' },
          { text: 'Human Resources', value: 'social_leadhr' },
          { text: 'Operations or Supply Chain', value: 'business_leadops' },
      ],
  },
  {
      id: 'c8',
      category: 'commerce',
      text: 'Success for you is defined by...',
      options: [
          { text: 'Achieving measurable financial targets.', value: 'analytical_targets' },
          { text: 'Building a beloved brand that customers trust.', value: 'creative_trust' },
          { text: 'Creating a thriving and happy workplace.', value: 'social_workplace' },
          { text: 'Developing a highly efficient and smooth-running organization.', value: 'business_efficiency' },
      ],
  },
  {
      id: 'c9',
      category: 'commerce',
      text: 'What tool would you rather use?',
      options: [
          { text: 'A spreadsheet full of financial data.', value: 'analytical_spreadsheet' },
          { text: 'A customer relationship management (CRM) software.', value: 'social_crm' },
          { text: 'A project management board like Trello or Jira.', value: 'business_project' },
          { text: 'A design tool like Canva or Adobe Express to create marketing materials.', value: 'creative_canva' },
      ],
  },
  {
      id: 'c10',
      category: 'commerce',
      text: 'In a team project, you are usually the one who...',
      options: [
          { text: 'Analyzes the numbers and keeps the budget in check.', value: 'analytical_budget' },
          { text: 'Comes up with the core creative concept.', value: 'creative_concept' },
          { text: 'Manages the team dynamics and ensures everyone is heard.', value: 'social_dynamics' },
          { text: 'Creates the plan and makes sure everyone sticks to the timeline.', value: 'business_plan' },
      ],
  },
  {
      id: 'c11',
      category: 'commerce',
      text: 'Which business headline catches your eye?',
      options: [
          { text: '"Company X Increases Profits by 20% Through Strategic Cost-Cutting"', value: 'analytical_headline' },
          { text: '"Startup Y Disrupts Market with Innovative New Product"', value: 'business_headline' },
          { text: '"Brand Z Voted Best Place to Work for Third Year in a Row"', value: 'social_headline' },
          { text: '"Ad Campaign for Product A Goes Viral, Reaching Millions"', value: 'creative_headline' },
      ],
  },
  {
      id: 'c12',
      category: 'commerce',
      text: 'I would rather...',
      options: [
          { text: 'Assess the risk of an investment portfolio.', value: 'analytical_portfolio' },
          { text: 'Develop a training program for new employees.', value: 'social_training' },
          { text: 'Plan a large-scale corporate event.', value: 'business_event' },
          { text: 'Research consumer needs for a new product.', value: 'social_research' },
      ],
  },
  {
      id: 'c13',
      category: 'commerce',
      text: 'You are driven by...',
      options: [
          { text: 'Logic and accuracy.', value: 'analytical_accuracy' },
          { text: 'Building relationships and networks.', value: 'social_relationships' },
          { text: 'Seeing a project through from start to finish.', value: 'business_completion' },
          { text: 'Imagination and fresh ideas.', value: 'creative_ideas' },
      ],
  },
  {
      id: 'c14',
      category: 'commerce',
      text: 'Which skill do you want to develop further?',
      options: [
          { text: 'Data analysis and statistical modeling.', value: 'analytical_dataskill' },
          { text: 'Public speaking and presentation.', value: 'social_presentationskill' },
          { text: 'Leadership and team management.', value: 'business_managementskill' },
          { text: 'Digital marketing and SEO.', value: 'creative_digitalseo' },
      ],
  },
  {
      id: 'c15',
      category: 'commerce',
      text: 'Your ideal work product is a...',
      options: [
          { text: 'Detailed report with clear data visualizations.', value: 'analytical_report_product' },
          { text: 'Successful marketing campaign with high engagement.', value: 'creative_campaign' },
          { text: 'A well-structured team or department.', value: 'social_team' },
          { text: 'A signed contract for a multi-million dollar deal.', value: 'business_deal' },
      ],
  },

  // Arts Questions
  {
    id: 'a1',
    category: 'arts',
    text: 'You express yourself best through...',
    options: [
      { text: 'Visuals - drawing, painting, or digital design.', value: 'creative_visual' },
      { text: 'Words - writing stories, articles, or arguments.', value: 'creative_writing' },
      { text: 'Performance - acting, music, or public speaking.', value: 'social_performance' },
      { text: 'Analysis - interpreting history, society, or literature.', value: 'humanities_analysis' },
    ],
  },
  {
    id: 'a2',
    category: 'arts',
    text: 'What kind of impact do you want to make?',
    options: [
      { text: 'Create work that is aesthetically beautiful and moves people.', value: 'creative_impact' },
      { text: 'Inform and persuade people through powerful arguments.', value: 'humanities_persuade' },
      { text: 'Shape public opinion and build relationships.', value: 'social_opinion' },
      { text: 'Advocate for justice and uphold the law.', value: 'humanities_justice' },
    ],
  },
   {
    id: 'a3',
    category: 'arts',
    text: 'Your ideal project would involve...',
    options: [
      { text: 'Designing the brand identity for a new company.', value: 'creative_identity' },
      { text: 'Writing a compelling narrative for a marketing campaign.', value: 'creative_narrative' },
      { text: 'Representing a client in a legal negotiation.', value: 'humanities_legal' },
      { text: 'Analyzing ancient texts to uncover historical insights.', value: 'humanities_historical' },
    ],
  },
  {
      id: 'a4',
      category: 'arts',
      text: 'You are most fascinated by...',
      options: [
          { text: 'How visual elements can influence emotion.', value: 'creative_emotion' },
          { text: 'The power of language and storytelling.', value: 'creative_storytelling' },
          { text: 'The structures of societies and governments.', value: 'humanities_society' },
          { text: 'The principles of justice and ethics.', value: 'humanities_ethics' },
      ],
  },
  {
      id: 'a5',
      category: 'arts',
      text: 'Which task would you enjoy the most?',
      options: [
          { text: 'Directing a short film.', value: 'creative_film' },
          { text: 'Writing an investigative journalism piece.', value: 'humanities_journalism' },
          { text: 'Curating an art exhibition at a museum.', value: 'creative_curate' },
          { text: 'Developing a public policy proposal to solve a social issue.', value: 'humanities_policy' },
      ],
  },
  {
      id: 'a6',
      category: 'arts',
      text: 'Your workspace would ideally be...',
      options: [
          { text: 'A creative studio filled with art supplies and inspiration.', value: 'creative_studio' },
          { text: 'A quiet library or archive, surrounded by books and documents.', value: 'humanities_library' },
          { text: 'A bustling newsroom or office, collaborating with a team.', value: 'social_newsroom' },
          { text: 'A courtroom or a government office.', value: 'humanities_courtroom' },
      ],
  },
  {
      id: 'a7',
      category: 'arts',
      text: 'You believe it\'s most important to be...',
      options: [
          { text: 'Original and innovative.', value: 'creative_original' },
          { text: 'Truthful and objective.', value: 'humanities_truthful' },
          { text: 'Empathetic and understanding.', value: 'social_empathetic' },
          { text: 'Logical and persuasive.', value: 'humanities_logical' },
      ],
  },
  {
      id: 'a8',
      category: 'arts',
      text: 'Which of these sounds like a compliment you\'d love to receive?',
      options: [
          { text: '"Your work is so visually stunning!"', value: 'creative_stunning' },
          { text: '"Your writing completely changed my perspective."', value: 'creative_perspective' },
          { text: '"You have a real gift for understanding and helping people."', value: 'social_gift' },
          { text: '"Your argument was impeccably researched and impossible to refute."', value: 'humanities_researched' },
      ],
  },
  {
      id: 'a9',
      category: 'arts',
      text: 'I am most skilled at...',
      options: [
          { text: 'Communicating ideas visually.', value: 'creative_communicating' },
          { text: 'Constructing a well-reasoned argument.', value: 'humanities_argument' },
          { text: 'Connecting with people on an emotional level.', value: 'social_connecting' },
          { text: 'Conducting in-depth research.', value: 'humanities_indepth' },
      ],
  },
  {
      id: 'a10',
      category: 'arts',
      text: 'Pick a tool:',
      options: [
          { text: 'A digital drawing tablet (e.g., Wacom).', value: 'creative_tablet' },
          { text: 'A library card with access to historical archives.', value: 'humanities_archives' },
          { text: 'A microphone and a recorder for interviews.', value: 'social_recorder' },
          { text: 'A book of legal statutes.', value: 'humanities_statutes' },
      ],
  },
  {
      id: 'a11',
      category: 'arts',
      text: 'You would rather spend a day...',
      options: [
          { text: 'Designing a poster for a music festival.', value: 'creative_poster' },
          { text: 'Helping students plan their future careers.', value: 'social_counseling' },
          { text: 'Translating a classic novel into another language.', value: 'humanities_translating' },
          { text: 'Managing a company\'s public image during a crisis.', value: 'social_crisis' },
      ],
  },
  {
      id: 'a12',
      category: 'arts',
      text: 'What is creativity to you?',
      options: [
          { text: 'The ability to produce something new and visually appealing.', value: 'creative_appealing' },
          { text: 'The ability to find new ways to tell important stories.', value: 'creative_important' },
          { text: 'The ability to solve human problems in novel ways.', value: 'social_novel' },
          { text: 'The ability to connect disparate ideas into a new theory.', value: 'humanities_theory' },
      ],
  },
  {
      id: 'a13',
      category: 'arts',
      text: 'You are drawn to stories about...',
      options: [
          { text: 'The lives of great artists.', value: 'creative_artists' },
          { text: 'Major historical events and their impact.', value: 'humanities_events' },
          { text: 'Social justice and human rights.', value: 'social_justice' },
          { text: 'The inner workings of the legal system.', value: 'humanities_legalstory' },
      ],
  },
  {
      id: 'a14',
      category: 'arts',
      text: 'Which skill is most valuable?',
      options: [
          { text: 'A great eye for aesthetics and design.', value: 'creative_aesthetics' },
          { text: 'The ability to write clearly and persuasively.', value: 'creative_persuasively' },
          { text: 'The ability to listen and offer wise counsel.', value: 'social_counsel' },
          { text: 'The ability to think critically and analyze complex texts.', value: 'humanities_critically' },
      ],
  },
  {
      id: 'a15',
      category: 'arts',
      text: 'Your favorite type of museum is...',
      options: [
          { text: 'An art museum with modern and classic works.', value: 'creative_artmuseum' },
          { text: 'A history museum with detailed exhibits on the past.', value: 'humanities_historymuseum' },
          { text: 'A science and industry museum with interactive displays.', value: 'technical_sciencemuseum' },
          { text: 'A cultural museum that explores different societies.', value: 'social_culturalmuseum' },
      ],
  },
];
