
export interface HonoursCourse {
    title: string;
    description: string;
    stream: string;
    credits: number;
    weeks: number;
}

export const honoursCourses: HonoursCourse[] = [
    // Computer Science & Engineering
    { title: 'The Joy of Computing using Python', description: 'Taught by Prof. Sudarshan Iyengar & Prof. Vayati Gupta.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Applied Natural Language Processing', description: 'Taught by Prof. Ramaseshan R.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Introduction to Algorithms and Analysis', description: 'Taught by Prof. Sourav Mukhopadhyay.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Bandit Algorithm (Online Machine Learning)', description: 'Taught by Prof. Manjesh Hanawal.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Deep Learning', description: 'Taught by Prof. Prabir Kumar Biswas.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Introduction to Industrial Internet of Things', description: 'Taught by Prof. Sudip Misra.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Introduction to Machine Learning', description: 'Taught by Prof. Balaraman Ravindran.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Operating System Fundamentals', description: 'Taught by Prof. Santanu Chattopadhyay.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Machine Learning for Engineering and Science Applications', description: 'Taught by Prof. Balaji Srinivasan & Prof. Ganapathy Krishnamurthi.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Computer Architecture and Organisation', description: 'Taught by Prof. Indranil Sengupta, Prof. Kamalika Datta.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Introduction to Industry 4.0 and Industrial Internet of Things', description: 'Taught by Prof. Sudip Misra.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Social Networks', description: 'Taught by Prof. Sudarshan Iyengar.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Artificial Intelligence Search Methods For Problem Solving', description: 'Taught by Prof. Deepak Khemani.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Fundamentals of Artificial Intelligence', description: 'Taught by Prof. Shyamanta M. Hazarika.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Hardware Modelling using Verilog', description: 'Taught by Prof. Indranil Sengupta.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Computer Graphics', description: 'Taught by Prof. Samit Bhattacharya.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Google Cloud Computing Foundation Course', description: 'Taught by Prof. Soumya Kanti Ghosh.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Data Base Management System', description: 'Taught by Prof. Partha Pratim Das, Prof. Samiran Chattopadhyay.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Cloud computing', description: 'Taught by Prof. Soumya Kanti Ghosh.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Programming, Data Structures And Algorithms Using Python', description: 'Taught by Prof. Madhavan Mukund.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Software Testing', description: 'Taught by Prof. Meenakshi D\'souza.', stream: 'Computer Science & Engineering', credits: 1, weeks: 4 },
    { title: 'Python for Data Science', description: 'Taught by Prof. Rengasamy.', stream: 'Computer Science & Engineering', credits: 1, weeks: 4 },
    { title: 'Introduction To Haskell Programming', description: 'A course on functional programming with Haskell.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'C Programming And Assembly Language', description: 'A course on C programming and assembly language.', stream: 'Computer Science & Engineering', credits: 1, weeks: 4 },
    { title: 'Natural Language Processing', description: 'An introductory course on Natural Language Processing.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Modern Algebra', description: 'A course on Modern Algebra.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Data Science For Engineers', description: 'A course on Data Science for engineering students.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Foundations Of Cryptography', description: 'A course on the foundations of cryptography.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Introduction To Soft Computing', description: 'A course on soft computing techniques.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Introduction To Internet Of Things', description: 'An introductory course on the Internet of Things.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Introduction To Blockchain Technology And Applications', description: 'An introductory course on blockchain technology.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Reinforcement Learning', description: 'A course on reinforcement learning.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Google Cloud Computing Foundations', description: 'Foundational course on Google Cloud.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Programming In Java', description: 'A comprehensive course on Java programming.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Getting Started With Competitive Programming', description: 'Learn the fundamentals of competitive programming.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Advanced Computer Networks', description: 'An advanced course on computer networks.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Advanced Graph Theory', description: 'An advanced course on graph theory.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Block Chain and its Applications', description: 'Learn about blockchain and its applications.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Circuit Complexity Theory', description: 'A course on circuit complexity theory.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Cloud Computing and Distributed Systems', description: 'A course on cloud and distributed systems.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Computational Number Theory and Algebra', description: 'A course on computational number theory and algebra.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Data Mining', description: 'An introductory course on data mining.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Digital Design with Verilog', description: 'A course on digital design using Verilog.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Edge Computing', description: 'An introductory course on edge computing.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Embedded System Design with ARM', description: 'Learn to design embedded systems with ARM.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Fundamental Algorithms: Design and Analysis', description: 'A course on fundamental algorithm design and analysis.', stream: 'Computer Science & Engineering', credits: 1, weeks: 4 },
    { title: 'Optimisation for Machine Learning: Theory and Implementation(Hindi)', description: 'Learn machine learning optimization in Hindi.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Parallel Computer Architecture', description: 'An advanced course on parallel computer architecture.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Quantum Algorithms and Cryptography', description: 'A course on quantum algorithms and cryptography.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Switching Circuits and Logic Design', description: 'A course on switching circuits and logic design.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Systems and Usable Security', description: 'A course on system security and usability.', stream: 'Computer Science & Engineering', credits: 1, weeks: 4 },
    { title: 'User-centric Computing For Human-Computer Interaction', description: 'Learn about user-centric computing for HCI.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Linear programming and its applications to computer science', description: 'A course on linear programming and its applications.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Affective Computing', description: 'A course on affective computing.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'AI: Constraint Satisfaction', description: 'A course on AI constraint satisfaction.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Data Analytics with Python', description: 'A course on data analytics using Python.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Discrete Mathematics - IITB', description: 'A course on discrete mathematics from IITB.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Foundations of Cyber Physical Systems', description: 'Learn the foundations of cyber-physical systems.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'GPU Architectures and Programming', description: 'A course on GPU architectures and programming.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Information Security - 5 - Secure Systems Engineering', description: 'A course on secure systems engineering.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Introduction to Embedded System Design', description: 'An introductory course on embedded system design.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Introduction To Soft Computing', description: 'An introductory course on soft computing.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },
    { title: 'Problem Solving Through Programming In C', description: 'Learn problem-solving using C programming.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Programming in Modern C++', description: 'A course on modern C++ programming.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Secure Computation: Part I', description: 'An introductory course on secure computation.', stream: 'Computer Science & Engineering', credits: 3, weeks: 12 },
    { title: 'Foundation of Cloud IoT Edge ML', description: 'An introductory course on the convergence of Cloud, IoT, Edge, and ML.', stream: 'Computer Science & Engineering', credits: 2, weeks: 8 },

    // Design Engineering
    { title: 'System Design for Sustainability', description: 'Taught by Prof. Sharmistha Banerjee.', stream: 'Design Engineering', credits: 3, weeks: 12 },
    { title: 'Functional and Conceptual Design', description: 'Taught by Prof. T. Asokan.', stream: 'Design Engineering', credits: 2, weeks: 8 },
    { title: 'Design, Technology and Innovation', description: 'Taught by Prof. B.K. Chakrabarty.', stream: 'Design Engineering', credits: 3, weeks: 12 },


    // Mathematics
    { title: 'Regression Analysis', description: 'Taught by Prof. Soumen Maity.', stream: 'Mathematics', credits: 3, weeks: 12 },
    { title: 'Computational Commutative Algebra', description: 'Taught by Prof. Manoj Kummini.', stream: 'Mathematics', credits: 3, weeks: 12 },
    { title: 'Scientific Computing using Matlab', description: 'Taught by Prof. Vivek K. Aggarwal & Prof. Arvind Kumar Lal.', stream: 'Mathematics', credits: 2, weeks: 8 },
    { title: 'Linear Algebra', description: 'Taught by Prof. P. N. Agrawal & Prof. D. N. Pandey.', stream: 'Mathematics', credits: 3, weeks: 12 },
    { title: 'Introduction to Fuzzy Set Theory, Arithmetic and Logic', description: 'Taught by Prof. Niladri Chatterjee.', stream: 'Mathematics', credits: 2, weeks: 8 },
    { title: 'Numerical methods', description: 'Taught by Prof. Ameeya Kumar Nayak, Prof. Sanjeev Kumar.', stream: 'Mathematics', credits: 2, weeks: 8 },
    { title: 'Essential Mathematics for Machine Learning', description: 'Taught by Prof. Sanjeev Kumar, Prof. S.K. Gupta.', stream: 'Mathematics', credits: 3, weeks: 12 },
    { title: 'Introduction to R Software', description: 'Taught by Prof. Shalabh.', stream: 'Mathematics', credits: 1, weeks: 4 },
    { title: 'Non-Parametric Statistical Inference', description: 'Taught by Prof. Niladri Chatterjee.', stream: 'Mathematics', credits: 3, weeks: 12 },
    { title: 'Operations Research', description: 'Taught by Prof. Kusum Deep.', stream: 'Mathematics', credits: 2, weeks: 8 },


    // Electrical & Electronics Engineering
    { title: 'Mapping Signal Processing Algorithms to DSP Architectures', description: 'Taught by Prof. Nitin Chandrachoodan.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Microelectronics: Devices to Circuits', description: 'Taught by Prof. Sudeb Dasgupta.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Op-Amp Practical Applications: Design, Simulation & Implementation', description: 'Taught by Prof. Hardik Jeetendra Pandya.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Sensors and Actuators', description: 'Taught by Prof. Hardik J Pandya.', stream: 'Electronics & Communication Engineering', credits: 2, weeks: 8 },
    { title: 'Pattern Recognition and Application', description: 'Taught by Prof. Prabir Kumar Biswas.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Applied Optimization for Wireless, Machine Learning, Big Data', description: 'Taught by Prof. Aditya K. Jagannatham.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Design of Photovoltaic Systems', description: 'Taught by Prof. L. Umanand.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Fabrication Techniques for MEMS-Based Sensors: Clinical Perspective', description: 'Taught by Prof. Hardik Jeetendra Pandya.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Introductory Neuroscience & Neuro-Instrumentation', description: 'Taught by Prof. Mahesh Jayachandra.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Advanced Linear Continuous Control Systems: Applications with MATLAB Programming and Simulink', description: 'Taught by Prof. Yogesh Vijay Hote.', stream: 'Electronics & Communication Engineering', credits: 3, weeks: 12 },
    { title: 'Fundamentals of Electronic Device Fabrication', description: 'Taught by Prof. Parasuraman Swaminathan.', stream: 'Electronics & Communication Engineering', credits: 2, weeks: 8 },
    { title: 'Introduction to Smart Grid', description: 'Taught by Prof. N.P. Padhy.', stream: 'Electrical Engineering', credits: 2, weeks: 8 },


    // Chemistry & Chemical Engineering
    { title: 'Spectroscopic Techniques for Pharmaceutical and Biopharmaceutical Industries', description: 'Taught by Prof. Shashank Deep.', stream: 'Chemistry', credits: 3, weeks: 12 },
    { title: 'Chemical Process Safety', description: 'Taught by Prof. Shishir Sinha.', stream: 'Chemical Engineering', credits: 2, weeks: 8 },
    { title: 'Technologies for Clean and Renewable Energy Production', description: 'Taught by Prof. P. Mondal.', stream: 'Chemical Engineering', credits: 3, weeks: 12 },

    // Biotechnology and Bioengineering
    { title: 'Drug Delivery: Principles and Applications', description: 'Taught by Prof. Rachit Agarwal.', stream: 'Biotechnology', credits: 3, weeks: 12 },
    { title: 'Genetic Engineering: Theory and Application', description: 'Taught by Prof. Vishal Trivedi.', stream: 'Biotechnology', credits: 3, weeks: 12 },
    { title: 'Fundamentals of Food Process Engineering', description: 'Taught by Prof. Jayeeta Mitra.', stream: 'Biotechnology', credits: 2, weeks: 8 },
    { title: 'Tissue Engineering', description: 'Taught by Prof. Vignesh Muthuvijayan.', stream: 'Biotechnology', credits: 3, weeks: 12 },
    { title: 'Biomaterials for Bone Tissue Engineering Applications', description: 'Taught by Prof. Biman B. Mandal.', stream: 'Biotechnology', credits: 3, weeks: 12 },
    { title: 'Biomedical Nanotechnology', description: 'Taught by Prof. P. Gopinath.', stream: 'Biotechnology', credits: 3, weeks: 12 },
    { title: 'Genetic Engineering: Theory And Application', description: 'A course on the theory and application of genetic engineering.', stream: 'Biotechnology', credits: 3, weeks: 12 },
    { title: 'Cellular Biophysics: A Framework For Quantitative Biology', description: 'A course on cellular biophysics and quantitative biology.', stream: 'Biotechnology', credits: 2, weeks: 8 },
    { title: 'Medical Image Analysis', description: 'A course on medical image analysis.', stream: 'Biotechnology', credits: 3, weeks: 12 },
    { title: 'Computer Aided Drug Design', description: 'A course on computer-aided drug design.', stream: 'Biotechnology', credits: 2, weeks: 8 },


    // Mechanical & Civil Engineering
    { title: 'Advanced Materials and Processes', description: 'Taught by Prof. Jayanta Das.', stream: 'Mechanical Engineering', credits: 3, weeks: 12 },
    { title: 'X-Ray Crystallography and Diffraction', description: 'Taught by Prof. Ranjit Kumar.', stream: 'Mechanical Engineering', credits: 2, weeks: 8 },
    { title: 'Finite Element Method: Variational Methods to Computer Programming', description: 'Taught by Prof. Atanu Banerjee, Prof. Arup Nandy.', stream: 'Mechanical Engineering', credits: 3, weeks: 12 },
    { title: 'Remote Sensing and GIS', description: 'Taught by Prof. Rishikesh Bharti.', stream: 'Civil Engineering', credits: 1, weeks: 4 },
    { title: 'Product Design and Development', description: 'Taught by Prof. Inderdeep Singh.', stream: 'Mechanical Engineering', credits: 3, weeks: 12 },


    // Humanities & Social Sciences
    { title: 'Patent Law for Engineers and Scientists', description: 'Taught by Prof. Feroz Ali.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Soft Skills', description: 'Taught by Prof. Binod Mishra.', stream: 'Humanities', credits: 1, weeks: 4 },
    { title: 'Science, Technology and Society', description: 'Taught by Prof. Sambit Mallick.', stream: 'Humanities', credits: 2, weeks: 8 },
    { title: 'Neuroscience of human movements', description: 'Taught by Prof. Varun.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Numerical Methods for Engineers', description: 'Taught by Prof. Niket Kaisare.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Learning Analytics Tools', description: 'Taught by Prof. Ramkumar Rajendran.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Health Research Fundamentals', description: 'Taught by Prof. P. Manickam.', stream: 'Humanities', credits: 2, weeks: 8 },
    { title: 'Consumer Psychology', description: 'Taught by Prof. Naveen Kashyap.', stream: 'Humanities', credits: 2, weeks: 8 },
    { title: 'Entrepreneurship and IP Strategy', description: 'Taught by Prof. Gouri Gargate.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Energy Economics and Policy', description: 'Taught by Prof. S. P. Das.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Technical English for Scientists and Engineers', description: 'Taught by Prof. Aysha Iqbal.', stream: 'Humanities', credits: 1, weeks: 4 },
    { title: 'Great Experiments in Psychology', description: 'Taught by Prof. Rajlakshmi Guha.', stream: 'Humanities', credits: 2, weeks: 8 },
    { title: 'Water, Society and Sustainability', description: 'Taught by Prof. Jenia Mukherjee.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Managing Intellectual Property in Universities', description: 'Taught by Prof. Feroz Ali.', stream: 'Humanities', credits: 3, weeks: 12 },
    { title: 'Patent Drafting for Beginners', description: 'Taught by Prof. Feroz Ali.', stream: 'Humanities', credits: 2, weeks: 8 },
    { title: 'Body language: Key to Professional Success', description: 'Taught by Prof. Rashmi Gaur.', stream: 'Humanities', credits: 1, weeks: 4 },
    { title: 'Developing Soft Skills and Personality', description: 'Taught by Prof. T. Ravichandran.', stream: 'Humanities', credits: 1, weeks: 4 },
    { title: 'Educational Leadership', description: 'Taught by Prof. Atasi Mohanty.', stream: 'Humanities', credits: 2, weeks: 8 },


    // Management
    { title: 'Human Resource Development', description: 'Taught by Prof. K.B.L. Srivastava.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Soft Skills for Business Negotiations and Marketing Strategies', description: 'Taught by Prof. Uttam Kumar Banerjee.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Industrial Safety Engineering', description: 'Taught by Prof. J. Maiti.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Working Capital Management', description: 'Taught by Prof. Anil K. Sharma.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Project Management for Managers', description: 'Taught by Prof. Mukesh Kumar Barua.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'International Business', description: 'Taught by Prof. J. K. Nayak.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Principles of Management', description: 'Taught by Prof. Susmita Mukhopadhyay, Prof. S. Srinivasan.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Decision Support System for Managers', description: 'Taught by Prof. Kunal Kanti Ghosh, Prof. Anupam Ghosh, Prof. Sujoy Bhattacharya.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Management Information System', description: 'Taught by Prof. Surojit Mukherjee.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Management Accounting', description: 'Taught by Prof. Anil K. Sharma.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Financial Accounting - IIT Mandi', description: 'Taught by Prof. Puran Singh.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Managing Service Operations', description: 'Taught by Prof. Jayanta Chatterjee.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Knowledge Management', description: 'Taught by Prof. K.B.L. Srivastava.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Ethics in Engineering Practice', description: 'Taught by Prof. Susmita Mukhopadhyay.', stream: 'Management', credits: 1, weeks: 4 },
    { title: 'Innovation, Business Models and Entrepreneurship', description: 'Taught by Prof. Rajat Agrawal, Prof. Vinay Sharma.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Marketing Research and Analysis', description: 'Taught by Prof. J.K. Nayak.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Financial Accounting - IITB', description: 'Taught by Prof. Varadraj Bapat.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Organization Development and Change in 21st Century', description: 'Taught by Prof. Ashish Pandey.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Customer Relationship Management', description: 'Taught by Prof. Swagato Chatterjee.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Introduction to Marketing Essentials', description: 'Taught by Prof. Z. Rahman.', stream: 'Management', credits: 1, weeks: 4 },
    { title: 'Business Analytics & Text Mining Modeling Using Python', description: 'Taught by Prof. Gaurav Dixit.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Marketing Management I', description: 'Taught by Prof. Jayanta Chatterjee, Prof. Shashi Shekhar Mishra.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Economics of Health and Health Care', description: 'Taught by Prof. Angan Sengupta.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Design Thinking - A Primer', description: 'Taught by Prof. Ashwin Mahalingam, Prof. Bala Ramadurai.', stream: 'Management', credits: 1, weeks: 4 },
    { title: 'Leadership', description: 'Taught by Prof. Kalyan Chakravarti, Prof. Tahoora Mukerjea.', stream: 'Management', credits: 2, weeks: 8 },
    { title: 'Business Analytics & Data Mining Modeling Using R Part II', description: 'Taught by Prof. Gaurav Dixit.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Cost Accounting', description: 'Taught by Prof. Varadraj Bapat.', stream: 'Management', credits: 3, weeks: 12 },
    { title: 'Decision Making Under Uncertainty', description: 'Taught by Prof. N. Gautam.', stream: 'Management', credits: 3, weeks: 12 },


    // Other / Multidisciplinary
    { title: 'Introduction to Research', description: 'Taught by Prof. Prathap Haridoss.', stream: 'Multidisciplinary', credits: 1, weeks: 4 },
    { title: 'Solar Energy Engineering and Technology', description: 'Taught by Prof. Pankaj Kalita.', stream: 'Physics', credits: 3, weeks: 12 },
    { title: 'Stress Management', description: 'Taught by Prof. Rajlakshmi Guha.', stream: 'Multidisciplinary', credits: 1, weeks: 4 },
    { title: 'Strategies for Learner-centric e-learning in STEM disciplines', description: 'Taught by Prof. Sahana Murthy.', stream: 'Multidisciplinary', credits: 2, weeks: 8 },
    { title: 'Teaching and Learning in General Programs: TALG', description: 'Taught by Prof. N J Rao.', stream: 'Multidisciplinary', credits: 3, weeks: 12 },
    { title: 'Global Navigation Satellite Systems And Applications', description: 'Taught by Prof. Arun K. Saraf.', stream: 'Earth Science', credits: 3, weeks: 12 },

    // Aerospace Engineering
    { title: 'Aircraft Stability And Control', description: 'A course on aircraft stability and control.', stream: 'Aerospace Engineering', credits: 3, weeks: 12 },
    { title: 'Introduction To Airplane Performance', description: 'An introductory course on airplane performance.', stream: 'Aerospace Engineering', credits: 2, weeks: 8 },
    { title: 'Introduction To Airbreathing Propulsion', description: 'An introductory course on air-breathing propulsion systems.', stream: 'Aerospace Engineering', credits: 3, weeks: 12 },
    { title: 'Design Of Fixed Wing Unmanned Aerial Vehicles', description: 'A course on designing fixed-wing UAVs.', stream: 'Aerospace Engineering', credits: 2, weeks: 8 },
    { title: 'Introduction To Aircraft Design', description: 'An introductory course on aircraft design principles.', stream: 'Aerospace Engineering', credits: 3, weeks: 12 },
    { title: 'Space Flight Mechanics', description: 'A course on the mechanics of space flight.', stream: 'Aerospace Engineering', credits: 3, weeks: 12 },
    { title: 'Vibration And Structural Dynamics', description: 'A course on vibration and structural dynamics in aerospace.', stream: 'Aerospace Engineering', credits: 2, weeks: 8 },
    { title: 'Aerodynamic Design Of Axial Flow Compressors & Fans', description: 'A course on the aerodynamic design of compressors and fans.', stream: 'Aerospace Engineering', credits: 3, weeks: 12 },
    { title: 'Introduction to Experiments in Flight', description: 'An introductory course on flight experiments.', stream: 'Aerospace Engineering', credits: 1, weeks: 4 }
];
